const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tabs=[['hero','Portada'],['works','Obras'],['murals','Murales'],['artist','Artista'],['videos','Videos'],['seo','SEO']];
let content=null,active='hero',dirty=false;

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMsg(text,type=''){const el=$('#loginMessage');el.textContent=text;el.className='msg '+type}
function setSave(text){$('#saveState').textContent=text||''}
function pathGet(path){return path.split('.').reduce((o,k)=>o?.[k],content)}
function pathSet(path,val){const parts=path.split('.');let o=content;parts.slice(0,-1).forEach(k=>o=o[k]);o[parts.at(-1)]=val;dirty=true;setSave('Cambios sin guardar')}
async function jsonFetch(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||`Error ${r.status}`),{status:r.status,data:d});return d}

async function authCheck(){try{const r=await fetch('/api/admin-auth',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(d.setupRequired){setMsg('Falta configurar la administración privada en Vercel. Añade SMART_ADMIN_PASSWORD y GITHUB_CONTENT_TOKEN y vuelve a desplegar.','error');return}if(d.authenticated)showApp()}catch(e){setMsg('No se pudo comprobar la sesión.','error')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();setMsg('Entrando…');try{await jsonFetch('/api/admin-auth',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});$('#adminPassword').value='';showApp()}catch(e){if(e.data?.setupRequired)setMsg('Primero hay que configurar las variables privadas en Vercel.','error');else setMsg(e.message,'error')}});
$('#logoutBtn').addEventListener('click',async()=>{await fetch('/api/admin-auth',{method:'DELETE',credentials:'same-origin'});location.reload()});

async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderTabs();await loadContent()}
async function loadContent(){try{const d=await jsonFetch('/api/admin-content',{cache:'no-store'});content=d.content;render();setSave('Guardado')}catch(e){if(e.status===401)return location.reload();$('#editor').innerHTML=`<div class="statusbox setup"><strong>No se pudo cargar el CMS.</strong><br>${esc(e.message)}</div>`}}
async function saveContent(){if(!content)return;setSave('Guardando…');try{await jsonFetch('/api/admin-content',{method:'PUT',body:JSON.stringify({content})});dirty=false;setSave('Guardado ✓')}catch(e){setSave('Error al guardar');alert(e.message)}}
$('#saveBtn').addEventListener('click',saveContent);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

function renderTabs(){const html=tabs.map(([k,l])=>`<button data-tab="${k}" class="${k===active?'active':''}">${l}</button>`).join('');$('#desktopTabs').innerHTML=html;$('#mobileTabs').innerHTML=html;$$('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;renderTabs();render()})}
function field(label,path,type='text',wide=false){const value=pathGet(path)??'';return `<label class="field ${wide?'wide':''}"><span>${label}</span>${type==='textarea'?`<textarea data-bind="${path}">${esc(value)}</textarea>`:`<input data-bind="${path}" value="${esc(value)}">`}</label>`}
function enabledBlock(section){return `<div class="panel switchrow"><div><div class="micro">Visibilidad</div><strong>Mostrar esta sección</strong></div><input data-bind="${section}.enabled" data-kind="boolean" type="checkbox" ${content[section].enabled!==false?'checked':''}></div>`}
function modeBlock(section,extra=''){const opts=[['single','Imagen única'],['gallery','Galería'],['carousel','Carrusel']];if(extra==='beforeAfter')opts.push(['beforeAfter','Antes / después']);return `<div class="panel"><div class="mode-row"><label class="field"><span>Presentación visual</span><select data-bind="${section}.mode">${opts.map(([v,l])=>`<option value="${v}" ${content[section].mode===v?'selected':''}>${l}</option>`).join('')}</select></label><div class="statusbox">Puedes cambiar este formato cuando quieras. <strong>No borra las imágenes</strong>; solo cambia cómo se muestran.</div></div></div>`}
function copyPanel(section,hasCtas=false){return `<div class="panel"><div class="panel-grid">${field('Eyebrow',`${section}.eyebrow`)}${field('Título',`${section}.title`)}${field('Texto',`${section}.body`,'textarea',true)}${hasCtas?field('CTA principal',`${section}.primaryLabel`)+field('CTA secundario',`${section}.secondaryLabel`):''}</div></div>`}
function sectionHead(title,body){return `<div class="editor-head"><div><div class="eyebrow">Contenido</div><h2>${title}</h2></div><p>${body}</p></div>`}

function mediaEditor(section){const list=content[section].images||[];return `<div class="panel"><div class="switchrow"><div><div class="micro">Biblioteca de la sección</div><h3 class="media-title">Imágenes</h3></div><span class="micro">${list.length} archivo${list.length===1?'':'s'}</span></div><div class="media-list">${list.map((im,i)=>`<div class="media-card"><div class="thumb"><img src="${esc(im.src)}" alt=""></div><div class="media-fields"><label class="field"><span>URL</span><input data-bind="${section}.images.${i}.src" value="${esc(im.src)}"></label><label class="field"><span>Alt text</span><input data-bind="${section}.images.${i}.alt" value="${esc(im.alt||'')}"></label><label class="field"><span>Leyenda</span><input data-bind="${section}.images.${i}.caption" value="${esc(im.caption||'')}"></label><div class="media-actions"><button class="btn ghost" data-move="up" data-section="${section}" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move="down" data-section="${section}" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-media data-section="${section}" data-index="${i}">Eliminar</button></div></div></div>`).join('')||'<div class="statusbox">No hay imágenes en esta sección.</div>'}</div><div class="uploadbar"><label class="btn dark">Subir imagen<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload="${section}"></label><button class="btn ghost" data-add-url="${section}">Añadir por URL</button></div><div class="preview-note">Al subir, el navegador reduce la imagen a un máximo de 2000 px y la convierte a WebP antes de enviarla al servidor.</div></div>`}

function renderHero(){return sectionHead('Portada','Controla el mensaje principal y decide si la entrada del sitio usa una sola obra, galería o carrusel.')+enabledBlock('hero')+modeBlock('hero')+copyPanel('hero',true)+mediaEditor('hero')}
function renderMurals(){return sectionHead('Murales','Edita el bloque comercial de murales y cambia entre imagen estática, galería, carrusel o antes/después.')+enabledBlock('murals')+modeBlock('murals','beforeAfter')+copyPanel('murals')+mediaEditor('murals')}
function renderArtist(){return sectionHead('Artista','Controla el bloque de Fernando y las imágenes de proceso vinculadas exclusivamente a su perfil.')+enabledBlock('artist')+modeBlock('artist')+copyPanel('artist')+mediaEditor('artist')}

function renderWorks(){const s=content.works,items=s.items||[];return sectionHead('Obras','Administra la selección comercial. Cada ficha puede tener imagen, nombre, descriptor, alt y CTA.')+enabledBlock('works')+modeBlock('works')+copyPanel('works')+`<div class="panel"><div class="switchrow"><h3 class="media-title">Fichas de obra</h3><span class="micro">${items.length} pieza${items.length===1?'':'s'}</span></div><div class="works-list">${items.map((it,i)=>`<div class="work-card"><img src="${esc(it.src)}" alt=""><div class="work-fields"><label class="field"><span>Título</span><input data-bind="works.items.${i}.title" value="${esc(it.title||'')}"></label><label class="field"><span>Descriptor</span><input data-bind="works.items.${i}.kicker" value="${esc(it.kicker||'')}"></label><label class="field wide"><span>URL de imagen</span><input data-bind="works.items.${i}.src" value="${esc(it.src||'')}"></label><label class="field wide"><span>Alt text</span><input data-bind="works.items.${i}.alt" value="${esc(it.alt||'')}"></label><label class="field wide"><span>CTA</span><input data-bind="works.items.${i}.cta" value="${esc(it.cta||'Consultar disponibilidad y precio')}"></label><div class="media-actions wide"><button class="btn ghost" data-move-work="up" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move-work="down" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-work data-index="${i}">Eliminar</button></div></div></div>`).join('')||'<div class="statusbox">No hay obras todavía.</div>'}</div><div class="uploadbar"><label class="btn dark">Subir obra<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload="works"></label><button class="btn ghost" data-add-work-url>Añadir por URL</button></div></div>`}

function renderVideos(){const s=content.videos,items=s.items||[];return sectionHead('Videos','Agrega YouTube, Vimeo o MP4. Puedes ocultarlos sin borrarlos y reordenarlos.')+enabledBlock('videos')+`<div class="panel"><div class="panel-grid">${field('Eyebrow','videos.eyebrow')}${field('Título','videos.title')}${field('Texto','videos.body','textarea',true)}</div></div><div class="panel"><div class="switchrow"><h3 class="media-title">Videos</h3><button class="btn dark" data-add-video>Agregar video</button></div><div style="margin-top:16px">${items.map((v,i)=>`<div class="video-row"><div class="video-info"><strong>${esc(v.title||'Video sin título')}</strong><small>${esc(v.url||'Sin URL')}</small><small>${v.published===false?'Oculto':'Publicado'}</small></div><div class="media-actions"><button class="btn ghost" data-edit-video="${i}">Editar</button><button class="btn ghost" data-toggle-video="${i}">${v.published===false?'Publicar':'Ocultar'}</button><button class="btn danger" data-remove-video="${i}">Eliminar</button></div></div>`).join('')||'<div class="statusbox">No hay videos todavía.</div>'}</div></div>`}
function renderSeo(){return sectionHead('SEO','Edita los metadatos principales. La home mantiene valores estáticos de respaldo para que el SEO no dependa de JavaScript.')+`<div class="panel"><div class="panel-grid">${field('Title SEO','seo.title', 'text',true)}${field('Meta description','seo.description','textarea',true)}</div><div class="statusbox">Mantén el título descriptivo y conciso. Evita repetir palabras clave artificialmente.</div></div>`}

function render(){if(!content)return;const views={hero:renderHero,works:renderWorks,murals:renderMurals,artist:renderArtist,videos:renderVideos,seo:renderSeo};$('#editor').innerHTML=views[active]();bindEditor()}
function bindEditor(){$$('[data-bind]').forEach(el=>{const evt=el.tagName==='SELECT'||el.type==='checkbox'?'change':'input';el.addEventListener(evt,()=>{let v=el.type==='checkbox'?el.checked:el.value;pathSet(el.dataset.bind,v)})});$$('[data-move]').forEach(b=>b.onclick=()=>moveMedia(b.dataset.section,+b.dataset.index,b.dataset.move));$$('[data-remove-media]').forEach(b=>b.onclick=()=>removeMedia(b.dataset.section,+b.dataset.index));$$('[data-add-url]').forEach(b=>b.onclick=()=>addUrl(b.dataset.addUrl));$$('[data-upload]').forEach(i=>i.onchange=()=>uploadFile(i.files?.[0],i.dataset.upload));$$('[data-move-work]').forEach(b=>b.onclick=()=>moveWork(+b.dataset.index,b.dataset.move));$$('[data-remove-work]').forEach(b=>b.onclick=()=>{content.works.items.splice(+b.dataset.index,1);markAndRender()});$('[data-add-work-url]')?.addEventListener('click',addWorkUrl);$('[data-add-video]')?.addEventListener('click',addVideo);$$('[data-edit-video]').forEach(b=>b.onclick=()=>editVideo(+b.dataset.editVideo));$$('[data-toggle-video]').forEach(b=>b.onclick=()=>{const v=content.videos.items[+b.dataset.toggleVideo];v.published=v.published===false?true:false;markAndRender()});$$('[data-remove-video]').forEach(b=>b.onclick=()=>{content.videos.items.splice(+b.dataset.removeVideo,1);markAndRender()})}
function markAndRender(){dirty=true;setSave('Cambios sin guardar');render()}
function move(arr,i,dir){const j=dir==='up'?i-1:i+1;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];markAndRender()}
function moveMedia(section,i,dir){move(content[section].images,i,dir)}
function removeMedia(section,i){if(confirm('¿Quitar esta imagen de la sección?')){content[section].images.splice(i,1);markAndRender()}}
function moveWork(i,dir){move(content.works.items,i,dir)}
function addUrl(section){const src=prompt('URL de la imagen');if(!src)return;const alt=prompt('Alt text (describe la obra o el proceso)')||'';content[section].images.push({src,alt,caption:''});markAndRender()}
function addWorkUrl(){const src=prompt('URL de la imagen');if(!src)return;content.works.items.push({title:'Nueva obra',kicker:'',src,alt:'',cta:'Consultar disponibilidad y precio'});markAndRender()}
function addVideo(){const title=prompt('Título del video');if(!title)return;const url=prompt('URL de YouTube, Vimeo o MP4');if(!url)return;content.videos.items.push({id:crypto.randomUUID(),title,url,description:'',published:true,order:(content.videos.items.length+1)*10});markAndRender()}
function editVideo(i){const v=content.videos.items[i];const title=prompt('Título',v.title||'');if(title===null)return;const url=prompt('URL',v.url||'');if(url===null)return;const description=prompt('Descripción',v.description||'');v.title=title;v.url=url;v.description=description??v.description;markAndRender()}

async function compressImage(file){const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>resolve(fr.result);fr.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=data});const max=2000,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});ctx.drawImage(img,0,0,w,h);return c.toDataURL('image/webp',.86)}
async function uploadFile(file,section){if(!file)return;setSave('Optimizando imagen…');try{const data=await compressImage(file);setSave('Subiendo imagen…');const r=await jsonFetch('/api/admin-media',{method:'POST',body:JSON.stringify({name:file.name,data})});if(section==='works')content.works.items.push({title:'Nueva obra',kicker:'',src:r.url,alt:'',cta:'Consultar disponibilidad y precio'});else content[section].images.push({src:r.url,alt:'',caption:''});dirty=true;setSave('Imagen subida · falta guardar contenido');render()}catch(e){setSave('Error al subir');alert(e.message)}}

authCheck();
