const owner='kr0dz',repo='san-miguel-art',branch='main',path='data/videos.json';
let token=sessionStorage.getItem('smart_gh_token')||'',sha='',videos=[];
const $=id=>document.getElementById(id);$('token').value=token;
function status(msg,type=''){const el=$('status');el.textContent=msg;el.className='dash-status '+type}
const headers=()=>({'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'});
function decode64(str){const bin=atob(str.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encode64(str){const bytes=new TextEncoder().encode(str);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
async function load(){if(!token)return;status('Conectando…');try{const r=await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`,{headers:headers()});if(!r.ok)throw new Error(`GitHub respondió ${r.status}`);const data=await r.json();sha=data.sha;videos=JSON.parse(decode64(data.content));sessionStorage.setItem('smart_gh_token',token);render();status('Conectado. Los cambios se guardarán en GitHub.','ok')}catch(e){status(e.message,'error')}}
async function save(message='Actualiza videos de Fernando Castañeda'){status('Guardando…');try{const r=await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`,{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({message,content:encode64(JSON.stringify(videos,null,2)+'\n'),sha,branch})});if(!r.ok){const t=await r.text();throw new Error(`No se pudo guardar (${r.status}): ${t.slice(0,180)}`)}const data=await r.json();sha=data.content.sha;render();status('Guardado. GitHub ya recibió el cambio.','ok')}catch(e){status(e.message,'error')}}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const root=$('videosList');if(!videos.length){root.innerHTML='<div class="empty">No hay videos todavía. Agrega el primero desde el formulario.</div>';return}root.innerHTML=videos.sort((a,b)=>(a.order||0)-(b.order||0)).map(v=>`<div class="video-row"><div><strong>${esc(v.title)}</strong><small>${esc(v.url)}</small>${v.description?`<small>${esc(v.description)}</small>`:''}</div><div><button class="btn" data-toggle="${v.id}">${v.published===false?'Publicar':'Ocultar'}</button> <button class="btn" data-delete="${v.id}">Eliminar</button></div></div>`).join('')}
$('connect').addEventListener('click',()=>{token=$('token').value.trim();load()});
$('videoForm').addEventListener('submit',async e=>{e.preventDefault();if(!token)return status('Primero conecta GitHub.','error');videos.push({id:crypto.randomUUID(),title:$('title').value.trim(),url:$('url').value.trim(),description:$('description').value.trim(),order:Number($('order').value)||10,published:true,createdAt:new Date().toISOString()});e.target.reset();$('order').value='10';await save('Agrega video de Fernando Castañeda')});
$('videosList').addEventListener('click',async e=>{const del=e.target.closest('[data-delete]');const tog=e.target.closest('[data-toggle]');if(del){if(!confirm('¿Eliminar este video?'))return;videos=videos.filter(v=>v.id!==del.dataset.delete);await save('Elimina video de Fernando Castañeda')}if(tog){const v=videos.find(v=>v.id===tog.dataset.toggle);if(v){v.published=v.published===false?true:false;await save('Actualiza visibilidad de video')}}});
if(token)load();
