const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let content=null,pageKey='home_es',view='page',dirty=false;
const sectionNames={services:'Servicios',gallery:'Galería / portafolio',process:'Proceso',feature:'Bloque destacado',faq:'Preguntas frecuentes',richtext:'Texto editorial',videos:'Videos',cta:'CTA final'};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMsg(t,type=''){const e=$('#loginMessage');e.textContent=t;e.className='msg '+type}
function setSave(t){$('#saveState').textContent=t||''}
function get(path){return path.split('.').reduce((o,k)=>o?.[k],content)}
function set(path,val){const parts=path.split('.');let o=content;parts.slice(0,-1).forEach(k=>{if(o[k]==null)o[k]={};o=o[k]});o[parts.at(-1)]=val;dirty=true;setSave('Cambios sin guardar')}
async function jf(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||`Error ${r.status}`),{status:r.status,data:d});return d}
async function authCheck(){try{const r=await fetch('/api/admin-auth',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(d.setupRequired)return setMsg('Falta la configuración privada en Vercel.','error');if(d.authenticated)showApp()}catch(e){setMsg('No se pudo comprobar la sesión.','error')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();setMsg('Entrando…');try{await jf('/api/admin-auth',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});$('#adminPassword').value='';showApp()}catch(e){setMsg(e.message,'error')}});
$('#logoutBtn').addEventListener('click',async()=>{await fetch('/api/admin-auth',{method:'DELETE',credentials:'same-origin'});location.reload()});
async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');await loadContent()}
async function loadContent(){try{const d=await jf('/api/admin-content',{cache:'no-store'});content=d.content;if(!content.pages)throw new Error('El contenido todavía no está migrado a V5.');renderChrome();render();setSave('Guardado')}catch(e){if(e.status===401)return location.reload();$('#editor').innerHTML=`<div class="statusbox setup"><strong>No se pudo cargar el CMS.</strong><br>${esc(e.message)}</div>`}}
async function save(){setSave('Guardando…');try{await jf('/api/admin-content',{method:'PUT',body:JSON.stringify({content})});dirty=false;setSave('Guardado ✓ · Vercel publicará el cambio')}catch(e){setSave('Error al guardar');alert(e.message)}}
$('#saveBtn').addEventListener('click',save);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
function page(){return content.pages[pageKey]}
function pfx(rest=''){return `pages.${pageKey}${rest?'.'+rest:''}`}
function field(label,path,type='text',wide=false,placeholder=''){const v=get(path)??'';return `<label class="field ${wide?'wide':''}"><span>${label}</span>${type==='textarea'?`<textarea data-bind="${path}" placeholder="${esc(placeholder)}">${esc(v)}</textarea>`:`<input data-bind="${path}" value="${esc(v)}" placeholder="${esc(placeholder)}">`}</label>`}
function selectField(label,path,opts,wide=false){const v=get(path);return `<label class="field ${wide?'wide':''}"><span>${label}</span><select data-bind="${path}">${opts.map(([x,l])=>`<option value="${x}" ${v===x?'selected':''}>${l}</option>`).join('')}</select></label>`}
function head(title,body){return `<div class="editor-head"><div><div class="eyebrow">SMArt V5</div><h2>${esc(title)}</h2></div><p>${esc(body||'')}</p></div>`}
function renderChrome(){const opts=Object.entries(content.pages).map(([k,p])=>`<option value="${k}" ${k===pageKey?'selected':''}>${esc(p.label)} · ${esc(p.lang)}</option>`).join('');let sel=$('#pageSelect');if(!sel){const top=$('.topbar');top.insertAdjacentHTML('afterbegin',`<select id="pageSelect" style="width:min(330px,40vw);margin-right:8px">${opts}</select>`);sel=$('#pageSelect')}else sel.innerHTML=opts;sel.value=pageKey;sel.onchange=()=>{pageKey=sel.value;view='page';renderChrome();render()};const p=page();const tabs=[['page','Página'],['hero','Hero'],...(p.sections||[]).map((s,i)=>[`section:${i}`,`${i+1}. ${sectionNames[s.type]||s.type}`]),['seo','SEO'],['global','Global']];const html=tabs.map(([k,l])=>`<button data-view="${k}" class="${k===view?'active':''}">${esc(l)}</button>`).join('');$('#desktopTabs').innerHTML=html;$('#mobileTabs').innerHTML=html;$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;renderChrome();render()});const preview=$('.topbar a.btn.ghost');if(preview)preview.href=p.path||'/'}
function commonPage(){const p=page();return head(p.label,'Edita los datos de esta URL y el orden de sus secciones. Los cambios se regeneran como HTML estático al publicar.')+`<div class="panel"><div class="panel-grid">${field('Nombre interno',pfx('label'))}${field('Ruta / URL',pfx('path'))}${field('Idioma',pfx('lang'))}${field('Ruta alternativa ES/EN',pfx('alternate'))}</div></div><div class="panel"><div class="switchrow"><div><div class="micro">Estructura</div><h3 class="media-title">Secciones de la página</h3></div><button class="btn dark" data-add-section>Añadir sección</button></div><div style="margin-top:16px">${(p.sections||[]).map((s,i)=>`<div class="video-row"><div class="video-info"><strong>${i+1}. ${esc(sectionNames[s.type]||s.type)}</strong><small>${esc(s.title||s.eyebrow||s.id||'Sin título')} · ${s.enabled===false?'Oculta':'Visible'}</small></div><div class="media-actions"><button class="btn ghost" data-open-section="${i}">Editar</button><button class="btn ghost" data-move-section="up" data-index="${i}">↑</button><button class="btn ghost" data-move-section="down" data-index="${i}">↓</button><button class="btn danger" data-remove-section="${i}">Eliminar</button></div></div>`).join('')}</div></div>`}
function imageEditor(path,list=[]){return `<div class="panel"><div class="switchrow"><h3 class="media-title">Imágenes</h3><span class="micro">${list.length}</span></div><div class="media-list">${list.map((im,i)=>`<div class="media-card"><div class="thumb"><img src="${esc(im.src)}" alt=""></div><div class="media-fields">${field('URL',`${path}.${i}.src`)}${field('Alt text',`${path}.${i}.alt`)}${field('Leyenda',`${path}.${i}.caption`)}<div class="media-actions"><button class="btn ghost" data-move-image="up" data-path="${path}" data-index="${i}">↑</button><button class="btn ghost" data-move-image="down" data-path="${path}" data-index="${i}">↓</button><button class="btn danger" data-remove-image data-path="${path}" data-index="${i}">Eliminar</button></div></div></div>`).join('')||'<div class="statusbox">No hay imágenes.</div>'}</div><div class="uploadbar"><label class="btn dark">Subir imagen<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload-image="${path}"></label><button class="btn ghost" data-add-image-url="${path}">Añadir URL</button></div></div>`}
function heroView(){const h=page().hero||{};return head('Hero · '+page().label,'Edita el primer impacto de esta página: SEO visible, mensaje, CTAs y presentación visual.')+`<div class="panel"><div class="panel-grid">${field('Eyebrow',pfx('hero.eyebrow'))}${field('Título / H1',pfx('hero.title'))}${field('Texto',pfx('hero.body'),'textarea',true)}${selectField('Presentación',pfx('hero.mode'),[['typographic','Tipográfico'],['single','Imagen única'],['gallery','Galería'],['carousel','Carrusel']])}</div></div><div class="panel"><div class="panel-grid">${field('CTA principal · etiqueta',pfx('hero.primary.label'))}${field('CTA principal · URL',pfx('hero.primary.href'))}${field('CTA principal · interés WhatsApp',pfx('hero.primary.interest'))}${field('CTA secundario · etiqueta',pfx('hero.secondary.label'))}${field('CTA secundario · URL',pfx('hero.secondary.href'))}${field('CTA secundario · interés WhatsApp',pfx('hero.secondary.interest'))}</div></div>${imageEditor(pfx('hero.images'),h.images||[])}`}
function commonSection(i,s){return `${head(`${sectionNames[s.type]||s.type} · ${page().label}`,'Edita esta sección, ocúltala o cambia su tratamiento visual.')}${`<div class="panel switchrow"><div><div class="micro">Visibilidad</div><strong>Mostrar sección</strong></div><input type="checkbox" data-bind="${pfx(`sections.${i}.enabled`)}" ${s.enabled!==false?'checked':''}></div>`}<div class="panel"><div class="panel-grid">${field('ID interno',pfx(`sections.${i}.id`))}${selectField('Tipo',pfx(`sections.${i}.type`),Object.entries(sectionNames).map(([k,v])=>[k,v]))}${field('Eyebrow',pfx(`sections.${i}.eyebrow`))}${field('Título',pfx(`sections.${i}.title`))}${field('Texto',pfx(`sections.${i}.body`),'textarea',true)}${selectField('Tema',pfx(`sections.${i}.theme`),[['','Claro'],['paper','Papel'],['dark','Oscuro']])}</div></div>`}
function itemsEditor(i,s){const base=pfx(`sections.${i}.items`),items=s.items||[];let html=`<div class="panel"><div class="switchrow"><h3 class="media-title">Elementos</h3><button class="btn dark" data-add-item="${i}">Añadir elemento</button></div><div class="works-list" style="margin-top:16px">`;
 html+=items.map((it,j)=>{const hasImage='src'in it||s.type==='gallery';return `<div class="work-card">${hasImage?`<div class="thumb"><img src="${esc(it.src||'')}" alt=""></div>`:`<div style="display:grid;place-items:center;background:#eee5d8;min-height:130px;font:42px var(--ser)">${String(j+1).padStart(2,'0')}</div>`}<div class="work-fields">${field('Etiqueta',`${base}.${j}.kicker`)}${field('Título',`${base}.${j}.title`)}${field('Texto',`${base}.${j}.body`,'textarea',true)}${hasImage?field('Imagen URL',`${base}.${j}.src`,'text',true):''}${hasImage?field('Alt text',`${base}.${j}.alt`,'text',true):''}${s.type==='services'?field('URL destino',`${base}.${j}.href`,'text',true):''}${['services','gallery'].includes(s.type)?field('CTA',`${base}.${j}.cta`,'text',true):''}${s.type==='videos'?field('URL video',`${base}.${j}.url`,'text',true):''}<div class="media-actions wide"><button class="btn ghost" data-move-item="up" data-section="${i}" data-index="${j}">↑</button><button class="btn ghost" data-move-item="down" data-section="${i}" data-index="${j}">↓</button>${hasImage?`<label class="btn ghost">Subir imagen<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload-item="${i}:${j}"></label>`:''}<button class="btn danger" data-remove-item="${i}:${j}">Eliminar</button></div></div></div>`}).join('');return html+'</div></div>'}
function sectionView(i){const s=page().sections[i];if(!s)return commonPage();let html=commonSection(i,s);const base=pfx(`sections.${i}`);if(s.type==='feature'){html+=`<div class="panel"><div class="panel-grid">${selectField('Layout',`${base}.layout`,[['media-left','Imagen izquierda'],['media-right','Imagen derecha']])}${selectField('Media',`${base}.mode`,[['single','Imagen única'],['gallery','Galería'],['carousel','Carrusel'],['beforeAfter','Antes / después']])}${field('CTA principal',`${base}.primary.label`)}${field('CTA principal URL',`${base}.primary.href`)}${field('CTA principal WhatsApp',`${base}.primary.interest`)}${field('CTA secundario',`${base}.secondary.label`)}${field('CTA secundario URL',`${base}.secondary.href`)}${field('CTA secundario WhatsApp',`${base}.secondary.interest`)}</div></div>${imageEditor(`${base}.images`,s.images||[])}`}
 else if(s.type==='cta'){html+=`<div class="panel"><div class="panel-grid">${field('Texto del botón',`${base}.cta`)}${field('Interés WhatsApp',`${base}.interest`)}</div></div>`}
 else if(s.type==='gallery'){html+=`<div class="panel">${selectField('Composición',`${base}.mode`,[['editorial','Editorial'],['masonry','Masonry'],['carousel','Carrusel']])}</div>`+itemsEditor(i,s)}
 else if(['services','process','faq','videos'].includes(s.type))html+=itemsEditor(i,s);
 return html}
function seoView(){return head('SEO · '+page().label,'Estos valores se escriben en el HTML estático durante el build de Vercel.')+`<div class="panel"><div class="panel-grid">${field('Title SEO',pfx('seo.title'),'text',true)}${field('Meta description',pfx('seo.description'),'textarea',true)}</div></div>`}
function navEditor(lang){const base=`globals.navigation.${lang}`,items=get(base)||[];return `<div class="panel"><div class="switchrow"><h3 class="media-title">Navegación ${lang.toUpperCase()}</h3><button class="btn dark" data-add-nav="${lang}">Añadir enlace</button></div><div style="margin-top:12px">${items.map((it,i)=>`<div class="video-row"><div style="display:grid;grid-template-columns:1fr 1.5fr;gap:10px;flex:1">${field('Etiqueta',`${base}.${i}.label`)}${field('URL',`${base}.${i}.href`)}</div><button class="btn danger" data-remove-nav="${lang}:${i}">Eliminar</button></div>`).join('')}</div></div>`}
function globalView(){return head('Global','Ajustes compartidos por todo el sitio. Los cambios aquí afectan todas las páginas.')+`<div class="panel"><div class="panel-grid">${field('Marca','globals.brand')}${field('WhatsApp','globals.whatsapp')}${field('Etiqueta de WhatsApp','globals.whatsappTag')}${selectField('Tema global','globals.design.theme',[['ivory','Marfil editorial'],['ink','Oscuro'],['sand','Arena']])}${field('Footer ES','globals.footer.es','textarea',true)}${field('Footer EN','globals.footer.en','textarea',true)}</div></div>${navEditor('es')}${navEditor('en')}`}
function render(){if(!content)return;let html=view==='page'?commonPage():view==='hero'?heroView():view==='seo'?seoView():view==='global'?globalView():view.startsWith('section:')?sectionView(+view.split(':')[1]):commonPage();$('#editor').innerHTML=html;bind();renderChrome()}
function bind(){$$('[data-bind]').forEach(el=>{const evt=el.type==='checkbox'||el.tagName==='SELECT'?'change':'input';el.addEventListener(evt,()=>set(el.dataset.bind,el.type==='checkbox'?el.checked:el.value))});$('[data-add-section]')?.addEventListener('click',()=>{const type=prompt('Tipo: services, gallery, process, feature, faq, richtext, videos o cta','services');if(!sectionNames[type])return alert('Tipo no válido');const s={id:`section-${Date.now()}`,type,enabled:true,eyebrow:'Nueva sección',title:'Título de sección',body:''};if(['services','gallery','process','faq','videos'].includes(type))s.items=[];if(type==='feature'){s.layout='media-left';s.mode='single';s.images=[];s.primary={label:'',href:'',interest:''}}if(type==='cta'){s.cta='Contactar';s.interest='Proyecto artístico'}page().sections.push(s);dirty=true;view=`section:${page().sections.length-1}`;setSave('Cambios sin guardar');render()});$$('[data-open-section]').forEach(b=>b.onclick=()=>{view=`section:${b.dataset.openSection}`;render()});$$('[data-move-section]').forEach(b=>b.onclick=()=>move(page().sections,+b.dataset.index,b.dataset.moveSection));$$('[data-remove-section]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta sección?')){page().sections.splice(+b.dataset.removeSection,1);dirty=true;view='page';setSave('Cambios sin guardar');render()}});$$('[data-move-image]').forEach(b=>b.onclick=()=>move(get(b.dataset.path),+b.dataset.index,b.dataset.moveImage));$$('[data-remove-image]').forEach(b=>b.onclick=()=>{get(b.dataset.path).splice(+b.dataset.index,1);mark()});$$('[data-add-image-url]').forEach(b=>b.onclick=()=>{const url=prompt('URL de imagen');if(!url)return;get(b.dataset.addImageUrl).push({src:url,alt:'',caption:''});mark()});$$('[data-upload-image]').forEach(i=>i.onchange=()=>uploadImage(i.files?.[0],url=>{get(i.dataset.uploadImage).push({src:url,alt:'',caption:''});mark()}));$$('[data-add-item]').forEach(b=>b.onclick=()=>addItem(+b.dataset.addItem));$$('[data-move-item]').forEach(b=>b.onclick=()=>move(page().sections[+b.dataset.section].items,+b.dataset.index,b.dataset.moveItem));$$('[data-remove-item]').forEach(b=>b.onclick=()=>{const [si,ii]=b.dataset.removeItem.split(':').map(Number);page().sections[si].items.splice(ii,1);mark()});$$('[data-upload-item]').forEach(i=>i.onchange=()=>{const [si,ii]=i.dataset.uploadItem.split(':').map(Number);uploadImage(i.files?.[0],url=>{page().sections[si].items[ii].src=url;mark()})});$$('[data-add-nav]').forEach(b=>b.onclick=()=>{content.globals.navigation[b.dataset.addNav].push({label:'Nuevo enlace',href:'/'});mark()});$$('[data-remove-nav]').forEach(b=>b.onclick=()=>{const [lang,i]=b.dataset.removeNav.split(':');content.globals.navigation[lang].splice(+i,1);mark()})}
function addItem(i){const s=page().sections[i];let item={title:'Nuevo elemento',body:''};if(s.type==='services')item={kicker:'Servicio',title:'Nuevo servicio',body:'',href:'/contacto/',cta:'Ver servicio'};if(s.type==='gallery')item={kicker:'Proyecto',title:'Nuevo proyecto',src:'',alt:'',cta:'Cotizar proyecto'};if(s.type==='process')item={title:'Nuevo paso',body:''};if(s.type==='faq')item={title:'Nueva pregunta',body:''};if(s.type==='videos')item={title:'Nuevo video',url:'',description:'',published:true};s.items.push(item);mark()}
function move(arr,i,dir){const j=dir==='up'?i-1:i+1;if(!arr||j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];mark()}
function mark(){dirty=true;setSave('Cambios sin guardar');render()}
async function compress(file){const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=data});const max=2000,sc=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*sc)),h=Math.max(1,Math.round(img.naturalHeight*sc));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(img,0,0,w,h);return c.toDataURL('image/webp',.86)}
async function uploadImage(file,done){if(!file)return;setSave('Optimizando imagen…');try{const data=await compress(file);setSave('Subiendo imagen…');const d=await jf('/api/admin-media',{method:'POST',body:JSON.stringify({name:file.name,data})});done(d.url);setSave('Imagen subida · guarda el contenido')}catch(e){setSave('Error al subir');alert(e.message)}}
authCheck();
