const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tabs=[['structure','Estructura'],['hero','Portada'],['services','Servicios'],['works','Portafolio'],['process','Proceso'],['murals','Murales'],['artist','Artista'],['videos','Videos'],['closing','Cierre'],['seo','SEO']];
const sectionLabels={hero:'Portada',services:'Servicios',works:'Portafolio',process:'Proceso',murals:'Murales',artist:'Artista',videos:'Videos',closing:'Cierre'};
let content=null,active='structure',dirty=false;

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setMsg(text,type=''){const el=$('#loginMessage');el.textContent=text;el.className='msg '+type}
function setSave(text){$('#saveState').textContent=text||''}
function pathGet(path){return path.split('.').reduce((o,k)=>o?.[k],content)}
function pathSet(path,val){const parts=path.split('.');let o=content;parts.slice(0,-1).forEach(k=>{if(o[k]==null)o[k]={};o=o[k]});o[parts.at(-1)]=val;dirty=true;setSave('Cambios sin guardar')}
async function jsonFetch(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||`Error ${r.status}`),{status:r.status,data:d});return d}

async function authCheck(){try{const r=await fetch('/api/admin-auth',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(d.setupRequired){setMsg('Falta configurar la administración privada en Vercel.','error');return}if(d.authenticated)showApp()}catch(e){setMsg('No se pudo comprobar la sesión.','error')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();setMsg('Entrando…');try{await jsonFetch('/api/admin-auth',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});$('#adminPassword').value='';showApp()}catch(e){setMsg(e.message,'error')}});
$('#logoutBtn').addEventListener('click',async()=>{await fetch('/api/admin-auth',{method:'DELETE',credentials:'same-origin'});location.reload()});
async function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderTabs();await loadContent()}
async function loadContent(){try{const d=await jsonFetch('/api/admin-content',{cache:'no-store'});content=d.content;ensureSchema();render();setSave('Guardado')}catch(e){if(e.status===401)return location.reload();$('#editor').innerHTML=`<div class="statusbox setup"><strong>No se pudo cargar el CMS.</strong><br>${esc(e.message)}</div>`}}
function ensureSchema(){content.navigation??={tagline:'San Miguel de Allende · Servicios artísticos',ctaLabel:'Cotizar proyecto'};content.design??={theme:'ivory',heroLayout:'editorial'};content.sectionOrder??=['hero','services','works','process','murals','artist','videos','closing'];content.services??={enabled:true,eyebrow:'Servicios',title:'Servicios artísticos',body:'',items:[]};content.process??={enabled:true,eyebrow:'Proceso',title:'Cómo trabajamos',body:'',ctaLabel:'Cotizar proyecto',steps:[]};content.closing??={enabled:true,eyebrow:'Contacto',title:'Cuéntanos sobre tu proyecto',body:'',ctaLabel:'Hablar por WhatsApp'}}
async function saveContent(){if(!content)return;setSave('Guardando…');try{await jsonFetch('/api/admin-content',{method:'PUT',body:JSON.stringify({content})});dirty=false;setSave('Guardado ✓')}catch(e){setSave('Error al guardar');alert(e.message)}}
$('#saveBtn').addEventListener('click',saveContent);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

function renderTabs(){const html=tabs.map(([k,l])=>`<button data-tab="${k}" class="${k===active?'active':''}">${l}</button>`).join('');$('#desktopTabs').innerHTML=html;$('#mobileTabs').innerHTML=html;$$('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;renderTabs();render()})}
function field(label,path,type='text',wide=false,placeholder=''){const value=pathGet(path)??'';return `<label class="field ${wide?'wide':''}"><span>${label}</span>${type==='textarea'?`<textarea data-bind="${path}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input data-bind="${path}" value="${esc(value)}" placeholder="${esc(placeholder)}">`}</label>`}
function selectField(label,path,options){const v=pathGet(path);return `<label class="field"><span>${label}</span><select data-bind="${path}">${options.map(([x,l])=>`<option value="${x}" ${v===x?'selected':''}>${l}</option>`).join('')}</select></label>`}
function enabledBlock(section){return `<div class="panel switchrow"><div><div class="micro">Visibilidad</div><strong>Mostrar esta sección</strong></div><input data-bind="${section}.enabled" type="checkbox" ${content[section].enabled!==false?'checked':''}></div>`}
function modeBlock(section,beforeAfter=false){const opts=[['single','Imagen única'],['gallery','Galería'],['carousel','Carrusel']];if(beforeAfter)opts.push(['beforeAfter','Antes / después']);return `<div class="panel"><div class="mode-row">${selectField('Presentación visual',`${section}.mode`,opts)}<div class="statusbox">Cambiar el modo no elimina imágenes; solo modifica cómo se presentan.</div></div></div>`}
function copyPanel(section,fields={cta:false,secondary:false}){return `<div class="panel"><div class="panel-grid">${field('Eyebrow',`${section}.eyebrow`)}${field('Título',`${section}.title`)}${field('Texto',`${section}.body`,'textarea',true)}${fields.cta?field('CTA',`${section}.ctaLabel`):''}${fields.secondary?field('CTA principal',`${section}.primaryLabel`)+field('CTA secundario',`${section}.secondaryLabel`):''}</div></div>`}
function sectionHead(title,body){return `<div class="editor-head"><div><div class="eyebrow">Editor visual</div><h2>${title}</h2></div><p>${body}</p></div>`}

function renderStructure(){const order=content.sectionOrder||[];return sectionHead('Estructura','Mueve secciones completas, ajusta la navegación y cambia el tratamiento visual global sin tocar código.')+`<div class="panel"><div class="panel-grid">${field('Subtítulo de marca','navigation.tagline')}${field('CTA del menú','navigation.ctaLabel')}${selectField('Tema visual','design.theme',[['ivory','Marfil editorial'],['ink','Contraste oscuro'],['sand','Arena contemporánea']])}${selectField('Composición del hero','design.heroLayout',[['editorial','Editorial asimétrico'],['cinematic','Imagen dominante'],['minimal','Minimal tipográfico']])}</div></div><div class="panel"><div class="switchrow"><div><div class="micro">Orden del home</div><h3 class="media-title">Secciones</h3></div><span class="micro">Arrastra conceptualmente con ↑ ↓</span></div><div style="margin-top:14px">${order.map((k,i)=>`<div class="video-row"><div class="video-info"><strong>${esc(sectionLabels[k]||k)}</strong><small>${content[k]?.enabled===false?'Oculta':'Visible'}</small></div><div class="media-actions"><button class="btn ghost" data-order="up" data-index="${i}">↑</button><button class="btn ghost" data-order="down" data-index="${i}">↓</button></div></div>`).join('')}</div></div>`}

function mediaEditor(section){const list=content[section].images||[];return `<div class="panel"><div class="switchrow"><div><div class="micro">Biblioteca de la sección</div><h3 class="media-title">Imágenes</h3></div><span class="micro">${list.length} archivo${list.length===1?'':'s'}</span></div><div class="media-list">${list.map((im,i)=>`<div class="media-card"><div class="thumb"><img src="${esc(im.src)}" alt=""></div><div class="media-fields"><label class="field"><span>URL</span><input data-bind="${section}.images.${i}.src" value="${esc(im.src)}"></label><label class="field"><span>Alt text</span><input data-bind="${section}.images.${i}.alt" value="${esc(im.alt||'')}"></label><label class="field"><span>Leyenda</span><input data-bind="${section}.images.${i}.caption" value="${esc(im.caption||'')}"></label><div class="media-actions"><button class="btn ghost" data-move="up" data-section="${section}" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move="down" data-section="${section}" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-media data-section="${section}" data-index="${i}">Eliminar</button></div></div></div>`).join('')||'<div class="statusbox">No hay imágenes en esta sección.</div>'}</div><div class="uploadbar"><label class="btn dark">Subir imagen<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload="${section}"></label><button class="btn ghost" data-add-url="${section}">Añadir por URL</button></div><div class="preview-note">Las imágenes se optimizan a WebP antes de subirlas. Usa alt text descriptivo, no nombres de personas visibles en la fotografía.</div></div>`}

function renderHero(){return sectionHead('Portada','Controla el mensaje principal, CTAs y la composición de imágenes del primer impacto.')+enabledBlock('hero')+modeBlock('hero')+copyPanel('hero',{secondary:true})+mediaEditor('hero')}
function renderMurals(){return sectionHead('Murales','Bloque comercial de muralismo. Puede usar imagen única, galería, carrusel o antes/después.')+enabledBlock('murals')+modeBlock('murals',true)+copyPanel('murals',{secondary:true})+mediaEditor('murals')}
function renderArtist(){return sectionHead('Artista','Edita el bloque del artista, texto, CTA y material visual asociado a su trabajo.')+enabledBlock('artist')+modeBlock('artist')+copyPanel('artist',{cta:true})+mediaEditor('artist')}

function renderServices(){const s=content.services,items=s.items||[];return sectionHead('Servicios','Cada servicio puede tener su propia landing, texto comercial y CTA. Puedes cambiar el orden o añadir nuevos.')+enabledBlock('services')+copyPanel('services')+`<div class="panel"><div class="switchrow"><h3 class="media-title">Servicios</h3><button class="btn dark" data-add-service>Añadir servicio</button></div><div class="works-list" style="margin-top:16px">${items.map((it,i)=>`<div class="work-card"><div style="display:grid;place-items:center;background:#f1eadf;min-height:150px;font:48px var(--ser)">${String(i+1).padStart(2,'0')}</div><div class="work-fields">${miniField('Etiqueta',`services.items.${i}.kicker`,it.kicker)}${miniField('Título',`services.items.${i}.title`,it.title)}${miniField('Texto',`services.items.${i}.body`,it.body,true)}${miniField('URL destino',`services.items.${i}.href`,it.href,true)}${miniField('CTA',`services.items.${i}.cta`,it.cta,true)}<div class="media-actions wide"><button class="btn ghost" data-move-service="up" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move-service="down" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-service="${i}">Eliminar</button></div></div></div>`).join('')}</div></div>`}
function miniField(label,path,val,wide=false){return `<label class="field ${wide?'wide':''}"><span>${label}</span><input data-bind="${path}" value="${esc(val||'')}"></label>`}

function renderWorks(){const s=content.works,items=s.items||[];return sectionHead('Portafolio','No es el negocio principal: úsalo como prueba visual. Administra imágenes, títulos, categorías y CTA de cada proyecto.')+enabledBlock('works')+modeBlock('works')+copyPanel('works')+`<div class="panel"><div class="switchrow"><h3 class="media-title">Proyectos</h3><span class="micro">${items.length} ficha${items.length===1?'':'s'}</span></div><div class="works-list">${items.map((it,i)=>`<div class="work-card"><img src="${esc(it.src)}" alt=""><div class="work-fields">${miniField('Título',`works.items.${i}.title`,it.title)}${miniField('Descriptor',`works.items.${i}.kicker`,it.kicker)}${miniField('URL de imagen',`works.items.${i}.src`,it.src,true)}${miniField('Alt text',`works.items.${i}.alt`,it.alt,true)}${miniField('CTA',`works.items.${i}.cta`,it.cta,true)}<div class="media-actions wide"><button class="btn ghost" data-move-work="up" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move-work="down" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-work data-index="${i}">Eliminar</button></div></div></div>`).join('')||'<div class="statusbox">No hay proyectos todavía.</div>'}</div><div class="uploadbar"><label class="btn dark">Subir proyecto<input class="upload-input" type="file" accept="image/jpeg,image/png,image/webp" data-upload="works"></label><button class="btn ghost" data-add-work-url>Añadir por URL</button></div></div>`}

function renderProcess(){const s=content.process,steps=s.steps||[];return sectionHead('Proceso','Edita el bloque que explica cómo se contrata el servicio. Puedes añadir, eliminar y ordenar pasos.')+enabledBlock('process')+copyPanel('process',{cta:true})+`<div class="panel"><div class="switchrow"><h3 class="media-title">Pasos</h3><button class="btn dark" data-add-step>Añadir paso</button></div><div style="margin-top:16px">${steps.map((st,i)=>`<div class="work-card"><div style="display:grid;place-items:center;background:#171512;color:#fff;min-height:130px;font:42px var(--ser)">${String(i+1).padStart(2,'0')}</div><div class="work-fields">${miniField('Título',`process.steps.${i}.title`,st.title,true)}<label class="field wide"><span>Texto</span><textarea data-bind="process.steps.${i}.body">${esc(st.body||'')}</textarea></label><div class="media-actions wide"><button class="btn ghost" data-move-step="up" data-index="${i}">↑ Subir</button><button class="btn ghost" data-move-step="down" data-index="${i}">↓ Bajar</button><button class="btn danger" data-remove-step="${i}">Eliminar</button></div></div></div>`).join('')}</div></div>`}

function renderVideos(){const s=content.videos,items=s.items||[];return sectionHead('Videos','Agrega YouTube, Vimeo o MP4. Puedes ocultarlos sin borrarlos y reordenarlos.')+enabledBlock('videos')+copyPanel('videos')+`<div class="panel"><div class="switchrow"><h3 class="media-title">Videos</h3><button class="btn dark" data-add-video>Agregar video</button></div><div style="margin-top:16px">${items.map((v,i)=>`<div class="video-row"><div class="video-info"><strong>${esc(v.title||'Video sin título')}</strong><small>${esc(v.url||'Sin URL')}</small><small>${v.published===false?'Oculto':'Publicado'}</small></div><div class="media-actions"><button class="btn ghost" data-edit-video="${i}">Editar</button><button class="btn ghost" data-toggle-video="${i}">${v.published===false?'Publicar':'Ocultar'}</button><button class="btn danger" data-remove-video="${i}">Eliminar</button></div></div>`).join('')||'<div class="statusbox">No hay videos todavía.</div>'}</div></div>`}
function renderClosing(){return sectionHead('Cierre','El último empujón comercial del home. Hazlo directo y orientado a contacto.')+enabledBlock('closing')+copyPanel('closing',{cta:true})}
function renderSeo(){return sectionHead('SEO','Metadatos principales del home. Los valores también existen como fallback estático para rastreo.')+`<div class="panel"><div class="panel-grid">${field('Title SEO','seo.title','text',true)}${field('Meta description','seo.description','textarea',true)}</div><div class="statusbox">Prioriza intención de contratación: murales, rótulos, pintura por encargo y San Miguel de Allende. Evita keyword stuffing.</div></div>`}

function render(){if(!content)return;const views={structure:renderStructure,hero:renderHero,services:renderServices,works:renderWorks,process:renderProcess,murals:renderMurals,artist:renderArtist,videos:renderVideos,closing:renderClosing,seo:renderSeo};$('#editor').innerHTML=views[active]();bindEditor()}
function bindEditor(){$$('[data-bind]').forEach(el=>{const evt=el.tagName==='SELECT'||el.type==='checkbox'?'change':'input';el.addEventListener(evt,()=>pathSet(el.dataset.bind,el.type==='checkbox'?el.checked:el.value))});$$('[data-order]').forEach(b=>b.onclick=()=>move(content.sectionOrder,+b.dataset.index,b.dataset.order));$$('[data-move]').forEach(b=>b.onclick=()=>move(content[b.dataset.section].images,+b.dataset.index,b.dataset.move));$$('[data-remove-media]').forEach(b=>b.onclick=()=>{if(confirm('¿Quitar esta imagen?')){content[b.dataset.section].images.splice(+b.dataset.index,1);markAndRender()}});$$('[data-add-url]').forEach(b=>b.onclick=()=>addUrl(b.dataset.addUrl));$$('[data-upload]').forEach(i=>i.onchange=()=>uploadFile(i.files?.[0],i.dataset.upload));$$('[data-move-work]').forEach(b=>b.onclick=()=>move(content.works.items,+b.dataset.index,b.dataset.move));$$('[data-remove-work]').forEach(b=>b.onclick=()=>{content.works.items.splice(+b.dataset.index,1);markAndRender()});$('[data-add-work-url]')?.addEventListener('click',addWorkUrl);$$('[data-move-service]').forEach(b=>b.onclick=()=>move(content.services.items,+b.dataset.index,b.dataset.move));$$('[data-remove-service]').forEach(b=>b.onclick=()=>{content.services.items.splice(+b.dataset.removeService,1);markAndRender()});$('[data-add-service]')?.addEventListener('click',()=>{content.services.items.push({kicker:'Nuevo servicio',title:'Servicio',body:'Descripción del servicio.',href:'/contacto/',cta:'Cotizar'});markAndRender()});$$('[data-move-step]').forEach(b=>b.onclick=()=>move(content.process.steps,+b.dataset.index,b.dataset.move));$$('[data-remove-step]').forEach(b=>b.onclick=()=>{content.process.steps.splice(+b.dataset.removeStep,1);markAndRender()});$('[data-add-step]')?.addEventListener('click',()=>{content.process.steps.push({title:'Nuevo paso',body:'Describe qué sucede en esta etapa.'});markAndRender()});$('[data-add-video]')?.addEventListener('click',addVideo);$$('[data-edit-video]').forEach(b=>b.onclick=()=>editVideo(+b.dataset.editVideo));$$('[data-toggle-video]').forEach(b=>b.onclick=()=>{const v=content.videos.items[+b.dataset.toggleVideo];v.published=v.published===false;markAndRender()});$$('[data-remove-video]').forEach(b=>b.onclick=()=>{content.videos.items.splice(+b.dataset.removeVideo,1);markAndRender()})}
function markAndRender(){dirty=true;setSave('Cambios sin guardar');render()}
function move(arr,i,dir){const j=dir==='up'?i-1:i+1;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];markAndRender()}
function addUrl(section){const src=prompt('URL de la imagen');if(!src)return;const alt=prompt('Alt text')||'';content[section].images??=[];content[section].images.push({src,alt,caption:''});markAndRender()}
function addWorkUrl(){const src=prompt('URL de la imagen');if(!src)return;content.works.items.push({title:'Nuevo proyecto',kicker:'',src,alt:'',cta:'Cotizar proyecto'});markAndRender()}
function addVideo(){const title=prompt('Título del video');if(!title)return;const url=prompt('URL de YouTube, Vimeo o MP4');if(!url)return;content.videos.items.push({id:crypto.randomUUID(),title,url,description:'',published:true,order:(content.videos.items.length+1)*10});markAndRender()}
function editVideo(i){const v=content.videos.items[i];const title=prompt('Título',v.title||'');if(title===null)return;const url=prompt('URL',v.url||'');if(url===null)return;const description=prompt('Descripción',v.description||'');v.title=title;v.url=url;v.description=description??v.description;markAndRender()}

async function compressImage(file){const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>resolve(fr.result);fr.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=data});const max=2000,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});ctx.drawImage(img,0,0,w,h);return c.toDataURL('image/webp',.86)}
async function uploadFile(file,target){if(!file)return;setSave('Optimizando imagen…');try{const data=await compressImage(file);setSave('Subiendo imagen…');const d=await jsonFetch('/api/admin-media',{method:'POST',body:JSON.stringify({dataUrl:data,fileName:file.name})});if(target==='works'){content.works.items.push({title:'Nuevo proyecto',kicker:'',src:d.url,alt:'',cta:'Cotizar proyecto'})}else{content[target].images??=[];content[target].images.push({src:d.url,alt:'',caption:''})}dirty=true;setSave('Imagen subida · falta guardar contenido');render()}catch(e){setSave('Error de imagen');alert(e.message)}}
authCheck();