const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data=null,tab='works',dirty=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function status(t){$('#status').textContent=t||''}
async function json(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||`Error ${r.status}`),{status:r.status});return d}
async function load(){try{const r=await json('/api/admin-marketplace',{cache:'no-store'});data=r.content;render();status('Guardado')}catch(e){if(e.status===401){location.href='/dashboard/';return}$('#content').innerHTML=`<div class="notice">No se pudo cargar el marketplace: ${esc(e.message)}</div>`}}
function field(label,path,value,type='text',wide=false){return `<label class="field ${wide?'wide':''}"><span>${esc(label)}</span>${type==='textarea'?`<textarea data-path="${path}">${esc(value||'')}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(value??'')}">`}</label>`}
function check(label,path,value){return `<label class="field"><span>${esc(label)}</span><select data-path="${path}"><option value="true" ${value!==false?'selected':''}>Sí</option><option value="false" ${value===false?'selected':''}>No</option></select></label>`}
function bind(){$$('[data-path]').forEach(el=>el.oninput=()=>{setPath(el.dataset.path,el.value);dirty=true;status('Cambios sin guardar')});$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$$('[data-add-artist]').forEach(b=>b.onclick=()=>{const n=(data.artists?.length||0)+1;data.artists.push({id:`artista-${Date.now()}`,slug:`artista-${n}`,name:'Nuevo artista',city:'San Miguel de Allende',disciplines:[],bioEs:'',bioEn:'',image:'',featured:false,published:false});dirty=true;tab='artists';render()});$$('[data-add-work]').forEach(b=>b.onclick=()=>{const a=data.artists?.[0]?.id||'';data.works.push({id:`obra-${Date.now()}`,slug:`obra-${(data.works?.length||0)+1}`,artistId:a,titleEs:'Nueva obra',titleEn:'New artwork',categoryEs:'',categoryEn:'',image:'',altEs:'',altEn:'',descriptionEs:'',descriptionEn:'',medium:'',dimensions:'',price:null,currency:'MXN',statusEs:'Consultar disponibilidad',statusEn:'Inquire for availability',featured:false,published:false});dirty=true;tab='works';render()});$$('[data-remove-artist]').forEach(b=>b.onclick=()=>{const i=+b.dataset.removeArtist;if(confirm('¿Eliminar este artista? Sus obras no se eliminarán automáticamente.')){data.artists.splice(i,1);dirty=true;render()}});$$('[data-remove-work]').forEach(b=>b.onclick=()=>{const i=+b.dataset.removeWork;if(confirm('¿Eliminar esta obra?')){data.works.splice(i,1);dirty=true;render()}});$$('[data-auto-slug]').forEach(b=>b.onclick=()=>{const [kind,i]=b.dataset.autoSlug.split(':');const item=kind==='artist'?data.artists[+i]:data.works[+i];item.slug=slug(kind==='artist'?item.name:item.titleEs);if(kind==='artist')item.id=item.id||item.slug;dirty=true;render()});$$('[data-upload]').forEach(inp=>inp.onchange=async()=>{const [kind,i]=inp.dataset.upload.split(':');const file=inp.files?.[0];if(!file)return;status('Subiendo imagen…');try{const dataUrl=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const up=await json('/api/admin-media',{method:'POST',body:JSON.stringify({name:file.name,data:dataUrl})});if(kind==='artist')data.artists[+i].image=up.url;else data.works[+i].image=up.url;dirty=true;status('Imagen subida · falta guardar catálogo');render()}catch(e){alert(e.message);status('Error al subir')}})}
function setPath(path,value){const parts=path.split('.');let o=data;for(const k of parts.slice(0,-1)){if(o[k]==null)o[k]={};o=o[k]}const key=parts.at(-1);if(value==='true'||value==='false')o[key]=value==='true';else if(key==='price')o[key]=value===''?null:Number(value);else if(key==='disciplines')o[key]=value.split(',').map(x=>x.trim()).filter(Boolean);else o[key]=value}
function renderArtists(){const cards=(data.artists||[]).map((a,i)=>`<div class="card"><div><div class="thumb">${a.image?`<img src="${esc(a.image)}" alt="">`:''}</div><div class="actions"><label class="btn ghost">Subir foto<input class="upload" type="file" accept="image/jpeg,image/png,image/webp" data-upload="artist:${i}"></label><button class="btn danger" data-remove-artist="${i}">Eliminar</button></div></div><div class="grid">${field('Nombre',`artists.${i}.name`,a.name)}${field('ID interno',`artists.${i}.id`,a.id)}${field('Slug URL',`artists.${i}.slug`,a.slug)}<div class="field"><span>Generar slug</span><button class="btn ghost" type="button" data-auto-slug="artist:${i}">Desde el nombre</button></div>${field('Ciudad',`artists.${i}.city`,a.city)}${field('Disciplinas (separadas por coma)',`artists.${i}.disciplines`,(a.disciplines||[]).join(', '), 'text',true)}${field('Bio ES',`artists.${i}.bioEs`,a.bioEs,'textarea',true)}${field('Bio EN',`artists.${i}.bioEn`,a.bioEn,'textarea',true)}${field('Imagen URL',`artists.${i}.image`,a.image,'text',true)}${check('Destacado',`artists.${i}.featured`,a.featured)}${check('Publicado',`artists.${i}.published`,a.published)}</div></div>`).join('');return `<div class="panel"><div class="list-head"><div><div class="eyebrow">Perfiles</div><h2>Artistas</h2></div><button class="btn dark" data-add-artist>Añadir artista</button></div>${cards||'<div class="notice">No hay artistas.</div>'}</div>`}
function artistOptions(selected){return (data.artists||[]).map(a=>`<option value="${esc(a.id)}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join('')}
function renderWorks(){const cards=(data.works||[]).map((w,i)=>`<div class="card"><div><div class="thumb">${w.image?`<img src="${esc(w.image)}" alt="">`:''}</div><div class="actions"><label class="btn ghost">Subir imagen<input class="upload" type="file" accept="image/jpeg,image/png,image/webp" data-upload="work:${i}"></label><button class="btn danger" data-remove-work="${i}">Eliminar</button></div></div><div class="grid">${field('Título ES',`works.${i}.titleEs`,w.titleEs)}${field('Título EN',`works.${i}.titleEn`,w.titleEn)}${field('ID interno',`works.${i}.id`,w.id)}${field('Slug URL',`works.${i}.slug`,w.slug)}<div class="field"><span>Generar slug</span><button class="btn ghost" type="button" data-auto-slug="work:${i}">Desde título ES</button></div><label class="field"><span>Artista</span><select data-path="works.${i}.artistId">${artistOptions(w.artistId)}</select></label>${field('Categoría ES',`works.${i}.categoryEs`,w.categoryEs)}${field('Categoría EN',`works.${i}.categoryEn`,w.categoryEn)}${field('Técnica',`works.${i}.medium`,w.medium)}${field('Medidas',`works.${i}.dimensions`,w.dimensions)}${field('Precio (vacío = consultar)',`works.${i}.price`,w.price??'','number')}${field('Moneda',`works.${i}.currency`,w.currency||'MXN')}${field('Disponibilidad ES',`works.${i}.statusEs`,w.statusEs)}${field('Disponibilidad EN',`works.${i}.statusEn`,w.statusEn)}${field('Descripción ES',`works.${i}.descriptionEs`,w.descriptionEs,'textarea',true)}${field('Descripción EN',`works.${i}.descriptionEn`,w.descriptionEn,'textarea',true)}${field('Imagen URL',`works.${i}.image`,w.image,'text',true)}${field('Alt ES',`works.${i}.altEs`,w.altEs,'text',true)}${field('Alt EN',`works.${i}.altEn`,w.altEn,'text',true)}${check('Destacada en home',`works.${i}.featured`,w.featured)}${check('Publicada',`works.${i}.published`,w.published)}</div></div>`).join('');return `<div class="panel"><div class="list-head"><div><div class="eyebrow">Catálogo</div><h2>Obras</h2></div><button class="btn dark" data-add-work>Añadir obra</button></div>${cards||'<div class="notice">No hay obras.</div>'}</div>`}
function renderSettings(){const s=data.settings||{};return `<div class="panel"><div class="list-head"><div><div class="eyebrow">Marketplace</div><h2>Ajustes</h2></div></div><div class="grid" style="margin-top:18px">${check('Marketplace activo','settings.enabled',s.enabled)}${field('Moneda predeterminada','settings.currency',s.currency||'MXN')}${field('CTA ES','settings.contactLabelEs',s.contactLabelEs)}${field('CTA EN','settings.contactLabelEn',s.contactLabelEn)}</div></div><div class="notice">Las fichas sin precio muestran “Consultar disponibilidad”. No inventes técnica, medidas, precio o disponibilidad: déjalos vacíos hasta tener el dato real.</div>`}
function render(){if(!data)return;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#content').innerHTML=tab==='artists'?renderArtists():tab==='settings'?renderSettings():renderWorks();bind()}
$('#save').onclick=async()=>{if(!data)return;status('Guardando…');try{await json('/api/admin-marketplace',{method:'PUT',body:JSON.stringify({content:data})});dirty=false;status('Guardado ✓ · Vercel publicará el catálogo')}catch(e){status('Error al guardar');alert(e.message)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
load();
