import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import path from 'node:path';

const ROOT=process.cwd();
const OUT=path.join(ROOT,'dist');
const data=JSON.parse(await readFile(path.join(ROOT,'data/site-v5.json'),'utf8'));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const isEn=p=>String(p.lang).toLowerCase().startsWith('en');
const abs=p=>`https://sanmigueldeallende.art${p}`;
const REF={hero:[355,42,423,303],botanical:[340,350,438,200],hotel:[29,799,164,146],restaurant:[211,799,155,146],signDetail:[382,799,160,146],house:[553,799,202,146],signCafe:[304,1023,422,167],hospitality:[39,1205,351,152],before:[40,1410,202,114],after:[286,1410,210,114],artist:[29,1671,169,137],sanmiguel:[379,1671,145,137]};
function isDefaultImage(src=''){return String(src).includes('/assets/reference/')}
function refCrop(key,alt='',caption=''){const [x,y,w,h]=REF[key],W=778,H=2022;const size=(W/w*100).toFixed(4),px=(x/(W-w)*100).toFixed(4),py=(y/(H-h)*100).toFixed(4);return `<figure class="figure ref-crop" style="--ratio:${w}/${h};--bgs:${size}%;--bgx:${px}%;--bgy:${py}%"><div class="ref-art" role="img" aria-label="${esc(alt)}"></div>${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`}
function regularFigure(im={}){return `<figure class="figure"><img src="${esc(im.src)}" alt="${esc(im.alt||'')}" loading="lazy">${im.caption?`<figcaption>${esc(im.caption)}</figcaption>`:''}</figure>`}
function media(images=[],mode='single'){const list=(images||[]).filter(x=>x?.src);if(!list.length)return'';if(mode==='beforeAfter')return`<div class="before-after">${list.slice(0,2).map(regularFigure).join('')}</div>`;if(mode==='gallery')return`<div class="gallery-media">${list.map(regularFigure).join('')}</div>`;if(mode==='carousel')return`<div class="carousel-media">${list.map(regularFigure).join('')}</div>`;return`<div class="single">${regularFigure(list[0])}</div>`}
function cta(obj={},solid=false){if(!obj?.label)return'';if(obj.href)return`<a class="button ${solid?'solid':''}" href="${esc(obj.href)}">${esc(obj.label)}</a>`;if(obj.interest)return`<button class="button ${solid?'solid':''}" data-interest="${esc(obj.interest)}">${esc(obj.label)}</button>`;return''}
function schemaFor(key,p){const graph=[{'@type':'WebPage','@id':abs(p.path)+'#webpage','url':abs(p.path),'name':p.seo.title,'description':p.seo.description,'inLanguage':p.lang},{'@type':'Organization','@id':'https://sanmigueldeallende.art/#organization','name':'SMArt','url':'https://sanmigueldeallende.art/'}];if(/murals|signs|commission|hospitality/.test(key))graph.push({'@type':'Service','name':p.hero?.title||p.label,'serviceType':p.label,'areaServed':{'@type':'City','name':'San Miguel de Allende'},'provider':{'@id':'https://sanmigueldeallende.art/#organization'},'url':abs(p.path)});return{'@context':'https://schema.org','@graph':graph}}
function head(p,key=''){const en=isEn(p),canonical=abs(p.path),other=p.alternate||'/';return `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.seo.title)}</title><meta name="description" content="${esc(p.seo.description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="${en?'en':'es-MX'}" href="${canonical}"><link rel="alternate" hreflang="${en?'es-MX':'en'}" href="${abs(other)}"><link rel="alternate" hreflang="x-default" href="https://sanmigueldeallende.art/"><meta property="og:type" content="website"><meta property="og:title" content="${esc(p.seo.title)}"><meta property="og:description" content="${esc(p.seo.description)}"><meta property="og:url" content="${canonical}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/v5.css"><link rel="stylesheet" href="/assets/css/reference.css"><script type="application/ld+json">${json(schemaFor(key,p))}</script></head>`}
function studioHeader(p,home=false){const en=isEn(p),other=p.alternate||'/';const labels=en?{murals:'Murals',signs:'Signs',projects:'Projects',process:'Process',artist:'About the artist',faq:'FAQ',quote:'Request a quote'}:{murals:'Murales',signs:'Rótulos',projects:'Proyectos',process:'Proceso',artist:'Sobre el artista',faq:'FAQ',quote:'Cotiza tu proyecto'};return `<header class="header reference-header"><a class="brand" href="${en?'/en/':'/'}">SMArt</a><nav class="nav"><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${labels.murals}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${labels.signs}</a><a href="${home?'#projects':(en?'/en/#projects':'/#projects')}">${labels.projects}</a><a href="${home?'#process':(en?'/en/#process':'/#process')}">${labels.process}</a><a href="${en?'/en/artists/fernando-castaneda/':'/artistas/fernando-castaneda/'}">${labels.artist}</a><a href="${home?'#faq':(en?'/en/murals-san-miguel-de-allende/#faq':'/murales-san-miguel-de-allende/#faq')}">${labels.faq}</a><a class="lang-link" href="${esc(other)}">${en?'ES':'EN'}</a><button class="nav-quote" data-interest="${en?'Art project':'Proyecto artístico'}">${labels.quote}</button></nav><button class="menu" aria-label="${en?'Open menu':'Abrir menú'}">☰</button></header><nav class="mobile-nav"><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${labels.murals}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${labels.signs}</a><a href="${home?'#projects':(en?'/en/#projects':'/#projects')}">${labels.projects}</a><a href="${home?'#process':(en?'/en/#process':'/#process')}">${labels.process}</a><a href="${en?'/en/artists/fernando-castaneda/':'/artistas/fernando-castaneda/'}">${labels.artist}</a><a href="${esc(other)}">${en?'Español':'English'}</a></nav>`}
function footer(p){const en=isEn(p),nav=data.globals.navigation[en?'en':'es']||[];return `<footer class="footer reference-footer"><div class="footer-intro"><div class="footer-brand">SMArt</div><p>${esc(data.globals.footer[en?'en':'es'])}</p></div><div class="footer-columns"><div><strong>${en?'Navigation':'Navegación'}</strong>${nav.slice(0,4).map(n=>`<a href="${esc(n.href)}">${esc(n.label)}</a>`).join('')}</div><div><strong>${en?'Services':'Servicios'}</strong><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'Murals':'Murales'}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${en?'Hand-painted signs':'Rótulos pintados a mano'}</a><a href="${en?'/en/commissioned-painting-san-miguel-de-allende/':'/pintura-por-encargo-san-miguel-de-allende/'}">${en?'Commissions':'Pintura por encargo'}</a></div><div><strong>San Miguel de Allende</strong><a href="${en?'/en/about/':'/sobre-smart/'}">${en?'About SMArt':'Sobre SMArt'}</a><a href="${en?'/en/contact/':'/contacto/'}">${en?'Contact':'Contacto'}</a></div><div><strong>${en?'Connect':'Conecta'}</strong><a href="#" data-interest="">WhatsApp</a><a href="${en?'/en/contact/':'/contacto/'}">Email</a></div></div></footer>`}
function wa(){return `<a class="whatsapp" href="#" data-interest="" aria-label="WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16.03 3.2A12.73 12.73 0 0 0 5.1 22.46L3.2 28.8l6.5-1.7a12.76 12.76 0 1 0 6.33-23.9Zm0 22.13c-2.12 0-4.08-.68-5.68-1.84l-.4-.28-3.86 1.01 1.03-3.76-.3-.4a9.37 9.37 0 1 1 9.21 5.27Zm5.15-7.02c-.28-.14-1.66-.82-1.92-.91-.26-.1-.45-.14-.64.14-.19.28-.73.91-.9 1.1-.16.18-.33.21-.61.07-.28-.14-1.19-.44-2.26-1.4a8.48 8.48 0 0 1-1.57-1.95c-.16-.28-.02-.43.12-.57.13-.13.28-.33.42-.49.14-.16.19-.28.28-.47.1-.19.05-.35-.02-.49-.07-.14-.64-1.54-.87-2.11-.23-.55-.47-.48-.64-.49h-.55c-.19 0-.49.07-.75.35-.26.28-.99.96-.99 2.35 0 1.38 1.01 2.72 1.15 2.91.14.19 1.99 3.04 4.82 4.26.67.29 1.2.46 1.61.59.68.22 1.29.19 1.78.12.54-.08 1.66-.68 1.9-1.34.23-.66.23-1.23.16-1.34-.07-.12-.26-.19-.54-.33Z"/></svg></a>`}
function bodyStart(p){return `<body data-whatsapp="${esc(data.globals.whatsapp)}" data-whatsapptag="${esc(data.globals.whatsappTag)}">`}
function normalImageOrRef(im,key){return im?.src&&!isDefaultImage(im.src)?regularFigure(im):refCrop(key,im?.alt||'',im?.caption||'')}
function icon(kind){const paths={mural:'<path d="M6 20c7-2 10-8 13-15M8 14c3 0 5 1 7 4M11 10c-2-2-3-4-2-6"/>',sign:'<path d="M6 8h12v9H6zM9 5h6M12 5v3M4 20h16"/>',commission:'<path d="M7 19 17 9l2 2L9 21H6zM15 7l2-2 2 2-2 2"/>',hotel:'<path d="M5 20V8l7-4 7 4v12M8 11h2m4 0h2M8 15h2m4 0h2M11 20v-4h2v4"/>'};return `<span class="service-icon"><svg viewBox="0 0 24 24" aria-hidden="true">${paths[kind]||paths.mural}</svg></span>`}
function botanical(){return `<figure class="figure botanical-svg" aria-label="Ilustración botánica decorativa"><svg viewBox="0 0 760 360" role="img"><g fill="none" stroke="currentColor" stroke-width="2"><path d="M55 330C210 205 330 160 700 48"/><path d="M230 237c-55-72-92-119-137-119 17 70 58 117 137 119Z"/><path d="M319 196c-22-88-13-144 28-178 24 72 16 130-28 178Z"/><path d="M397 160c45-76 98-112 154-100-38 62-89 96-154 100Z"/><path d="M483 125c9-79 45-124 102-137 0 70-34 116-102 137Z"/><path d="M542 103c64-48 117-59 160-31-53 42-104 52-160 31Z"/></g></svg></figure>`}
function homePage(p){
 const en=isEn(p),sections=Object.fromEntries((p.sections||[]).map(s=>[s.id,s])),services=sections.services||{},portfolio=sections.portfolio||{},murals=sections.murals||{},process=sections.process||{},artist=sections.artist||{},closing=sections.closing||{};
 const signs=data.pages[en?'signs_en':'signs_es']||{},hospitality=data.pages[en?'hospitality_en':'hospitality_es']||{};
 const h=p.hero||{},heroImage=(h.images||[])[0];
 const hTitle=h.title|| (en?'Hand-painted murals and signs in San Miguel de Allende':'Murales y rótulos pintados a mano en San Miguel de Allende');
 const hEyebrow=h.eyebrow|| (en?'MURALS · SIGNS · SAN MIGUEL DE ALLENDE':'MURALES Y RÓTULOS PINTADOS A MANO');
 const hBody=h.body|| (en?'We transform walls, facades and spaces into one-of-a-kind pieces made for each place.':'Transformamos muros, fachadas y espacios en obras únicas, hechas con tiempo, oficio y pensadas para cada lugar.');
 const serviceItems=(services.items||[]).slice(0,4),portfolioItems=(portfolio.items||[]).slice(0,4),fallbackProjects=['hotel','restaurant','signDetail','house'];
 const projectDefaults=en?[['Boutique hotel','Interior mural'],['Restaurant','Hand-painted sign'],['Coffee shop','Glass sign'],['Private house','Exterior mural']]:[['Hotel boutique','Mural interior'],['Restaurante','Rótulo pintado a mano'],['Cafetería','Rótulo sobre vidrio'],['Casa particular','Mural exterior']];
 const processItems=(process.items||[]).slice(0,4);while(processItems.length<4)processItems.push(en?{title:['Conversation','Design','Painting','Enjoy'][processItems.length],body:['We listen to your idea and understand the space.','We create a visual proposal for the project.','The work is painted by hand on site.','A unique intervention becomes part of the space.'][processItems.length]}:{title:['Conversamos','Diseñamos','Pintamos','Disfrutas'][processItems.length],body:['Escuchamos tu idea, entendemos el espacio y tus objetivos.','Creamos una propuesta visual a la medida del proyecto.','Pintamos a mano con técnicas y materiales adecuados.','Entregamos una obra única que transforma el espacio.'][processItems.length]});
 const muralImgs=murals.images||[],sameInterior=muralImgs.length>=2&&muralImgs[0]?.src===muralImgs[1]?.src&&String(muralImgs[0]?.src||'').includes('interior-board.webp');
 const beforeIm=sameInterior?{src:'/assets/images/fernando/interior-before.webp',alt:'Antes de la intervención mural',caption:'ANTES'}:muralImgs[0];
 const afterIm=sameInterior?{src:'/assets/images/fernando/interior-after.webp',alt:'Después de la intervención mural',caption:'DESPUÉS'}:muralImgs[1];
 const artistIm=(artist.images||[])[0],signsIm=(signs.hero?.images||[])[0],hospIm=(hospitality.hero?.images||[])[0];
 const primary=h.primary||{},secondary=h.secondary||{};
 const heroButtons=`${cta(primary,true)}${cta(secondary,false)}`||`<button class="button solid" data-interest="${en?'Mural or sign project':'Mural o rótulo'}">${en?'REQUEST A QUOTE':'COTIZAR MI PROYECTO'}</button><a class="button" href="#projects">${en?'VIEW PROJECTS':'VER PROYECTOS'}</a>`;
 return `<!doctype html><html lang="${esc(p.lang)}">${head(p,en?'home_en':'home_es')}${bodyStart(p)}${studioHeader(p,true)}<main class="reference-home">
 <section class="ref-hero"><div class="ref-hero-copy"><div class="eyebrow">${esc(hEyebrow)}</div><h1>${esc(hTitle)}</h1><p>${esc(hBody)}</p><div class="hero-actions">${heroButtons}</div></div><div class="ref-hero-art">${heroImage?.src?regularFigure(heroImage):refCrop('hero',hTitle)}</div></section>
 <section class="manifesto"><div class="manifesto-copy"><h2>${esc(services.title|| (en?'A wall can be much more than a wall.':'Un muro puede ser mucho más que una pared.'))}</h2><i></i><p>${esc(services.body|| (en?'Every project begins with a place, a story and an intention.':'Cada proyecto nace de un lugar, una historia y una intención.'))}</p><a href="${en?'/en/about/':'/sobre-smart/'}">${en?'DISCOVER OUR PHILOSOPHY':'CONOCE NUESTRA FILOSOFÍA'} →</a></div><div class="manifesto-art">${botanical()}</div></section>
 <section class="ref-services"><div class="mini-heading">${en?'WHAT WE DO':'LO QUE HACEMOS'}</div><div class="ref-service-grid">${serviceItems.map((it,i)=>`<a class="ref-service" href="${esc(it.href||'#')}">${icon(['mural','sign','commission','hotel'][i])}<h3>${String(i+1).padStart(2,'0')}. ${esc(it.title||'')}</h3><p>${esc(it.body||'')}</p><span>${esc(it.cta||(en?'VIEW MORE':'VER MÁS'))} →</span></a>`).join('')}</div></section>
 <section class="ref-projects" id="projects"><div class="ref-section-title"><h2>${esc(portfolio.title|| (en?'PROJECTS THAT TRANSFORM SPACES':'PROYECTOS QUE TRANSFORMAN ESPACIOS'))}</h2><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'VIEW ALL PROJECTS':'VER TODOS LOS PROYECTOS'} →</a></div><div class="ref-project-grid">${[0,1,2,3].map(i=>{const it=portfolioItems[i]||{},d=projectDefaults[i];return `<article class="ref-project">${it.src?regularFigure(it):refCrop(fallbackProjects[i],it.alt||d[1])}<div><small>${esc(it.kicker||d[0])}</small><strong>${esc(it.title||d[1])}</strong><button data-interest="${esc(it.title||d[1])}">${en?'VIEW PROJECT':'VER PROYECTO'} →</button></div></article>`}).join('')}</div></section>
 <section class="ref-split sign-block"><div class="ref-split-copy"><h2>${en?'HAND-PAINTED SIGNS FOR BUSINESSES IN SAN MIGUEL DE ALLENDE':'RÓTULOS PINTADOS A MANO PARA NEGOCIOS EN SAN MIGUEL DE ALLENDE'}</h2><i></i><p>${esc(signs.hero?.body||'')}</p><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${en?'VIEW SIGN PROJECTS':'VER EJEMPLOS DE RÓTULOS'} →</a></div><div class="ref-split-art">${signsIm?.src?regularFigure(signsIm):regularFigure({src:'/assets/images/fernando/abstract-board.webp',alt:en?'Hand-painted visual project':'Proyecto visual pintado a mano'})}</div></section>
 <section class="ref-split hospitality-block"><div class="ref-split-art">${hospIm?.src?regularFigure(hospIm):regularFigure({src:'/assets/images/fernando/atardecer-board.webp',alt:en?'Mural in an interior space':'Mural integrado a un espacio interior'})}</div><div class="ref-split-copy"><h2>${en?'SPACES PEOPLE REMEMBER':'MURALES PARA HOTELES, RESTAURANTES Y ESPACIOS QUE INSPIRAN'}</h2><i></i><p>${esc(hospitality.hero?.body||'')}</p><a href="${en?'/en/hotel-restaurant-murals-san-miguel-de-allende/':'/murales-hoteles-restaurantes-san-miguel-de-allende/'}">${en?'VIEW HOSPITALITY PROJECTS':'VER PROYECTOS DE HOSPITALIDAD'} →</a></div></section>
 <section class="transformation"><div class="mini-heading">${en?'FROM IDEA TO WALL':'DE LA IDEA A LA PARED'}</div><div class="transformation-grid"><div class="ref-before-after before-after">${beforeIm?.src?regularFigure(beforeIm):refCrop('before',en?'Before mural':'Antes del mural','ANTES')}${afterIm?.src?regularFigure(afterIm):refCrop('after',en?'After mural':'Después del mural','DESPUÉS')}</div><div class="transform-copy"><h3>${en?'Every project begins with a vision and becomes something real.':'Cada proyecto comienza con una visión y se convierte en algo real.'}</h3><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'SEE MORE TRANSFORMATIONS':'VER MÁS TRANSFORMACIONES'} →</a></div></div></section>
 <section class="ref-process" id="process"><div class="mini-heading">${en?'OUR PROCESS':'NUESTRO PROCESO'}</div><ol>${processItems.map((it,i)=>`<li><b>${String(i+1).padStart(2,'0')}</b><h3>${esc(it.title)}</h3><p>${esc(it.body)}</p></li>`).join('')}</ol></section>
 <section class="artist-place"><div class="artist-grid"><div class="artist-photo">${artistIm?.src?regularFigure(artistIm):regularFigure({src:'/assets/images/fernando/artist.webp',alt:en?'Artist working on a mural':'Artista trabajando en un mural'})}</div><div class="artist-copy"><h2>${en?'PAINTED BY HAND. DESIGNED TO BELONG.':'PINTADO A MANO. DISEÑADO PARA PERTENECER AL LUGAR.'}</h2><p>${esc(artist.body||'')}</p><a href="${en?'/en/artists/fernando-castaneda/':'/artistas/fernando-castaneda/'}">${en?'MEET THE ARTIST':'CONOCE AL ARTISTA'} →</a></div><div class="place-photo">${regularFigure({src:'/assets/images/fernando/parroquia-board.webp',alt:'San Miguel de Allende'})}</div><div class="place-copy"><h2>${en?'MURALS AND SIGNS IN SAN MIGUEL DE ALLENDE':'MURALES Y RÓTULOS EN SAN MIGUEL DE ALLENDE'}</h2><p>${en?'San Miguel is color, history and culture. Our work is designed to belong to its architecture and atmosphere.':'San Miguel es color, historia y cultura. Los murales y rótulos se diseñan para dialogar con su arquitectura, su atmósfera y la identidad de cada espacio.'}</p><a href="${en?'/en/about/':'/sobre-smart/'}">${en?'MORE ABOUT SAN MIGUEL':'VER MÁS SOBRE SAN MIGUEL'} →</a></div></div></section>
 <section class="ref-faq" id="faq"><div class="mini-heading">FAQ</div><div class="faq-inline"><h2>${en?'Questions before starting?':'¿Preguntas antes de empezar?'}</h2><a href="${en?'/en/murals-san-miguel-de-allende/#faq':'/murales-san-miguel-de-allende/#faq'}">${en?'SEE FREQUENTLY ASKED QUESTIONS':'VER PREGUNTAS FRECUENTES'} →</a></div></section>
 <section class="ref-final"><h2>${esc(closing.title|| (en?'DO YOU HAVE A WALL IN MIND?':'¿TIENES UNA PARED EN MENTE?'))}</h2><p>${esc(closing.body||'')}</p><div><button class="button solid" data-interest="${esc(closing.interest||'Proyecto artístico')}">${esc(closing.cta|| (en?'REQUEST A QUOTE':'COTIZA TU PROYECTO'))}</button><button class="button dark-outline" data-interest="${esc(closing.interest||'Proyecto artístico')}">${en?'WHATSAPP US':'ESCRÍBENOS POR WHATSAPP'}</button></div></section>
 </main>${footer(p)}${wa()}<script src="/assets/js/site-v5.js" defer></script></body></html>`}
function headBlock(s){return`<div class="section-head"><div><div class="eyebrow">${esc(s.eyebrow||'')}</div><h2>${esc(s.title||'')}</h2></div>${s.body?`<p>${esc(s.body)}</p>`:''}</div>`}
function renderServices(s){return`<section class="section ${s.theme==='paper'?'paper':''}" data-section="${esc(s.id)}">${headBlock(s)}<div class="services-list">${(s.items||[]).map((it,i)=>`<a class="service-row" href="${esc(it.href||'#')}"><span class="idx">${String(i+1).padStart(2,'0')}</span><span class="kicker">${esc(it.kicker||'')}</span><h3>${esc(it.title||'')}</h3><p>${esc(it.body||'')}</p><span class="arrow">${esc(it.cta||'Explore')} ↗</span></a>`).join('')}</div></section>`}
function renderGallery(s){const cls=s.mode==='masonry'?'masonry':s.mode==='carousel'?'carousel':'';return`<section class="section" data-section="${esc(s.id)}">${headBlock(s)}<div class="portfolio ${cls}">${(s.items||[]).map(it=>`<article class="project"><div class="project-image"><img src="${esc(it.src||'')}" alt="${esc(it.alt||'')}" loading="lazy"></div><div class="project-info"><span>${esc(it.kicker||'')}</span><h3>${esc(it.title||'')}</h3>${it.cta?`<button class="text-link" data-interest="${esc(it.title||it.cta)}">${esc(it.cta)} ↗</button>`:''}</div></article>`).join('')}</div></section>`}
function renderProcess(s){return`<section class="section" data-section="${esc(s.id)}">${headBlock(s)}<ol class="process-list">${(s.items||[]).map((it,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(it.title||'')}</strong><p>${esc(it.body||'')}</p></div></li>`).join('')}</ol></section>`}
function renderFeature(s){const layout=s.layout==='media-left'?'media-left':'media-right';return`<section class="feature ${layout}" data-section="${esc(s.id)}"><div class="feature-copy"><div class="eyebrow">${esc(s.eyebrow||'')}</div><h2>${esc(s.title||'')}</h2>${s.body?`<p>${esc(s.body)}</p>`:''}<div class="feature-actions">${cta(s.primary,true)}${cta(s.secondary,false)}</div></div><div class="feature-media">${media(s.images,s.mode)}</div></section>`}
function renderFaq(s){return`<section class="section" id="faq" data-section="${esc(s.id)}"><div class="faq"><div class="eyebrow">${esc(s.eyebrow||'')}</div><h2>${esc(s.title||'')}</h2>${(s.items||[]).map(it=>`<details><summary>${esc(it.title||'')}</summary><p>${esc(it.body||'')}</p></details>`).join('')}</div></section>`}
function renderRich(s){return`<section class="section paper" data-section="${esc(s.id)}"><div class="richtext"><div><div class="eyebrow">${esc(s.eyebrow||'')}</div><h2>${esc(s.title||'')}</h2></div><div class="copy">${esc(s.body||'')}</div></div></section>`}
function renderVideos(s,en){const items=(s.items||[]).filter(v=>v?.published!==false&&v?.url);if(!items.length)return'';return`<section class="section paper" data-section="${esc(s.id)}">${headBlock(s)}<div class="videos">${items.map(v=>`<article class="video-card"><div class="video-copy"><h3>${esc(v.title||'Video')}</h3><p>${esc(v.description||'')}</p><a href="${esc(v.url)}" target="_blank" rel="noopener">${en?'Watch video':'Ver video'} ↗</a></div></article>`).join('')}</div></section>`}
function renderCta(s){return`<section class="cta-section" data-section="${esc(s.id)}"><div class="eyebrow">${esc(s.eyebrow||'')}</div><h2>${esc(s.title||'')}</h2>${s.body?`<p>${esc(s.body)}</p>`:''}<button class="button solid" data-interest="${esc(s.interest||s.cta||'Proyecto artístico')}">${esc(s.cta||'WhatsApp')}</button></section>`}
function renderSection(s,en){if(s.enabled===false)return'';switch(s.type){case'services':return renderServices(s);case'gallery':return renderGallery(s);case'process':return renderProcess(s);case'feature':return renderFeature(s);case'faq':return renderFaq(s);case'richtext':return renderRich(s);case'videos':return renderVideos(s,en);case'cta':return renderCta(s);default:return''}}
function genericHero(p){const h=p.hero||{},typ=h.mode==='typographic'||!(h.images||[]).length;return`<section class="hero ${typ?'typographic':''}"><div class="hero-copy"><div class="eyebrow">${esc(h.eyebrow||'')}</div><h1>${esc(h.title||'')}</h1>${h.body?`<p>${esc(h.body)}</p>`:''}<div class="hero-actions">${cta(h.primary,true)}${cta(h.secondary,false)}</div></div>${typ?'':`<div class="hero-media">${media(h.images,h.mode)}</div>`}</section>`}
function genericPage(key,p){const en=isEn(p);return `<!doctype html><html lang="${esc(p.lang)}">${head(p,key)}${bodyStart(p)}${studioHeader(p,false)}<main>${genericHero(p)}${(p.sections||[]).map(s=>renderSection(s,en)).join('')}</main>${footer(p)}${wa()}<script src="/assets/js/site-v5.js" defer></script></body></html>`}
await rm(OUT,{recursive:true,force:true});await mkdir(OUT,{recursive:true});await cp(path.join(ROOT,'assets'),path.join(OUT,'assets'),{recursive:true});await cp(path.join(ROOT,'dashboard'),path.join(OUT,'dashboard'),{recursive:true});
for(const [key,p] of Object.entries(data.pages)){const rel=p.path==='/'?'index.html':path.join(p.path.replace(/^\//,'').replace(/\/$/,''),'index.html');const file=path.join(OUT,rel);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,key==='home_es'||key==='home_en'?homePage(p):genericPage(key,p),'utf8')}
const urls=Object.values(data.pages).map(p=>`<url><loc>${abs(p.path)}</loc><lastmod>${new Date().toISOString().slice(0,10)}</lastmod></url>`).join('');await writeFile(path.join(OUT,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`);await writeFile(path.join(OUT,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /dashboard/\nSitemap: https://sanmigueldeallende.art/sitemap.xml\n`);console.log(`Built ${Object.keys(data.pages).length} CMS pages into dist/`);