import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';

const ROOT=process.cwd();
const OUT=path.join(ROOT,'dist');
const market=JSON.parse(await readFile(path.join(ROOT,'data/marketplace.json'),'utf8'));
const site=JSON.parse(await readFile(path.join(ROOT,'data/site-v5.json'),'utf8'));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const abs=p=>`https://sanmigueldeallende.art${p}`;
const publishedArtists=(market.artists||[]).filter(x=>x.published!==false);
const publishedWorks=(market.works||[]).filter(x=>x.published!==false);
const artistById=id=>publishedArtists.find(a=>a.id===id)||{};
const wa=site.globals?.whatsapp||'447915374776';
const tag=site.globals?.whatsappTag||'ART';

function whatsapp(text){return `https://wa.me/${wa}?text=${encodeURIComponent(`${text}\n\n[${tag}]`)}`}
function commonHead({lang='es-MX',title,description,pathname,type='website',schema={}}){
 const en=lang.startsWith('en');
 return `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${abs(pathname)}"><meta property="og:type" content="${esc(type)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${abs(pathname)}"><link rel="icon" type="image/svg+xml" href="/assets/brand/favicon.svg"><link rel="shortcut icon" href="/assets/brand/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/v5.css"><link rel="stylesheet" href="/assets/css/reference.css"><link rel="stylesheet" href="/assets/css/reference-final.css"><link rel="stylesheet" href="/assets/css/marketplace.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org',...schema}).replace(/</g,'\\u003c')}</script></head>`;
}
function marketHeader(en=false){
 return `<header class="header reference-header"><a class="brand" href="${en?'/en/':'/'}">SMArt</a><nav class="nav"><a href="${en?'/en/artworks/':'/obras/'}">${en?'Artworks':'Obras'}</a><a href="${en?'/en/artists/':'/artistas/'}">${en?'Artists':'Artistas'}</a><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'Murals':'Murales'}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${en?'Signs':'Rótulos'}</a><a href="${en?'/en/commissioned-painting-san-miguel-de-allende/':'/pintura-por-encargo-san-miguel-de-allende/'}">${en?'Commissions':'Encargos'}</a><a href="${en?'/':'/en/'}">${en?'ES':'EN'}</a><a class="nav-quote" href="${en?'/en/for-artists/':'/para-artistas/'}">${en?'For artists':'Soy artista'}</a></nav><button class="menu" aria-label="${en?'Open menu':'Abrir menú'}">☰</button></header><nav class="mobile-nav"><a href="${en?'/en/artworks/':'/obras/'}">${en?'Artworks':'Obras'}</a><a href="${en?'/en/artists/':'/artistas/'}">${en?'Artists':'Artistas'}</a><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'Murals':'Murales'}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${en?'Signs':'Rótulos'}</a><a href="${en?'/en/for-artists/':'/para-artistas/'}">${en?'For artists':'Soy artista'}</a><a href="${en?'/':'/en/'}">${en?'Español':'English'}</a></nav>`;
}
function marketFooter(en=false){return `<footer class="footer reference-footer"><div class="footer-intro"><div class="footer-brand">SMArt</div><p>${en?'Art, artists and custom projects in San Miguel de Allende.':'Arte, artistas y proyectos por encargo en San Miguel de Allende.'}</p></div><div class="footer-columns"><div><strong>${en?'Discover':'Descubrir'}</strong><a href="${en?'/en/artworks/':'/obras/'}">${en?'Artworks':'Obras'}</a><a href="${en?'/en/artists/':'/artistas/'}">${en?'Artists':'Artistas'}</a><a href="${en?'/en/for-artists/':'/para-artistas/'}">${en?'For artists':'Para artistas'}</a></div><div><strong>${en?'Services':'Servicios'}</strong><a href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'Murals':'Murales'}</a><a href="${en?'/en/hand-painted-signs-san-miguel-de-allende/':'/rotulos-san-miguel-de-allende/'}">${en?'Hand-painted signs':'Rótulos pintados a mano'}</a><a href="${en?'/en/commissioned-painting-san-miguel-de-allende/':'/pintura-por-encargo-san-miguel-de-allende/'}">${en?'Commissions':'Pintura por encargo'}</a></div><div><strong>San Miguel de Allende</strong><a href="${en?'/en/about/':'/sobre-smart/'}">${en?'About SMArt':'Sobre SMArt'}</a><a href="${en?'/en/contact/':'/contacto/'}">${en?'Contact':'Contacto'}</a></div><div><strong>${en?'Connect':'Conecta'}</strong><a href="${whatsapp(en?'Hello, I would like information about SMArt.':'Hola, quiero información sobre SMArt.')}" target="_blank" rel="noopener">WhatsApp</a></div></div></footer>`}
function workCard(w,en=false){const a=artistById(w.artistId);return `<a class="market-card" data-category="${esc(en?w.categoryEn:w.categoryEs)}" href="${en?'/en/artworks/':'/obras/'}${esc(w.slug)}/"><div class="market-card-media"><img src="${esc(w.image)}" alt="${esc(en?w.altEn:w.altEs)}" loading="lazy"></div><div class="market-card-body"><div class="market-card-meta"><span>${esc(a.name)}</span><span>${esc(en?w.categoryEn:w.categoryEs)}</span></div><h3>${esc(en?w.titleEn:w.titleEs)}</h3><div class="market-card-status">${esc(en?w.statusEn:w.statusEs)} →</div></div></a>`}
function shell({en=false,head,body}){return `<!doctype html><html lang="${en?'en':'es-MX'}">${head}<body data-whatsapp="${esc(wa)}" data-whatsapptag="${esc(tag)}">${marketHeader(en)}${body}${marketFooter(en)}<a class="whatsapp" href="${whatsapp(en?'Hello, I would like information about SMArt.':'Hola, quiero información sobre SMArt.')}" target="_blank" rel="noopener" aria-label="WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16.03 3.2A12.73 12.73 0 0 0 5.1 22.46L3.2 28.8l6.5-1.7a12.76 12.76 0 1 0 6.33-23.9Zm0 22.13c-2.12 0-4.08-.68-5.68-1.84l-.4-.28-3.86 1.01 1.03-3.76-.3-.4a9.37 9.37 0 1 1 9.21 5.27Zm5.15-7.02c-.28-.14-1.66-.82-1.92-.91-.26-.1-.45-.14-.64.14-.19.28-.73.91-.9 1.1-.16.18-.33.21-.61.07-.28-.14-1.19-.44-2.26-1.4a8.48 8.48 0 0 1-1.57-1.95c-.16-.28-.02-.43.12-.57.13-.13.28-.33.42-.49.14-.16.19-.28.28-.47.1-.19.05-.35-.02-.49-.07-.14-.64-1.54-.87-2.11-.23-.55-.47-.48-.64-.49h-.55c-.19 0-.49.07-.75.35-.26.28-.99.96-.99 2.35 0 1.38 1.01 2.72 1.15 2.91.14.19 1.99 3.04 4.82 4.26.67.29 1.2.46 1.61.59.68.22 1.29.19 1.78.12.54-.08 1.66-.68 1.9-1.34.23-.66.23-1.23.16-1.34-.07-.12-.26-.19-.54-.33Z"/></svg></a><script src="/assets/js/site-v5.js" defer></script></body></html>`}
async function writeRoute(route,html){const rel=route.replace(/^\//,'').replace(/\/$/,'');const dir=path.join(OUT,rel);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),html,'utf8')}
function categories(en=false){return [...new Set(publishedWorks.map(w=>en?w.categoryEn:w.categoryEs).filter(Boolean))]}
function worksIndex(en=false){const pathname=en?'/en/artworks/':'/obras/';const title=en?'Art for Sale in San Miguel de Allende | Artists & Artworks | SMArt':'Arte en Venta en San Miguel de Allende | Obras de Artistas | SMArt';const description=en?'Discover artworks and artists in San Miguel de Allende and inquire directly about availability, commissions and custom projects.':'Descubre obras y artistas en San Miguel de Allende. Consulta disponibilidad, piezas, comisiones y proyectos artísticos directamente con SMArt.';const cards=publishedWorks.map(w=>workCard(w,en)).join('');const filters=categories(en).map(x=>`<button class="market-filter" data-filter="${esc(x)}">${esc(x)}</button>`).join('');const body=`<main class="market-page"><section class="market-page-hero"><div><div class="market-kicker">${en?'CURATED IN SAN MIGUEL DE ALLENDE':'ARTE EN SAN MIGUEL DE ALLENDE'}</div><h1>${en?'Artworks to discover and collect.':'Obras para descubrir y coleccionar.'}</h1></div><p>${en?'A growing selection of local artists, artwork and commissioned projects. Each listing connects directly with SMArt for availability and details.':'Una selección en crecimiento de artistas locales, obra y proyectos por encargo. Cada ficha conecta directamente con SMArt para consultar disponibilidad y detalles.'}</p></section><div class="market-filters"><button class="market-filter active" data-filter="*">${en?'All':'Todo'}</button>${filters}</div><section class="market-index-grid">${cards}</section><section class="market-artist-cta"><div><div class="market-kicker">${en?'ARE YOU AN ARTIST?':'¿ERES ARTISTA?'}</div><h2>${en?'Put your work in front of people looking for art in San Miguel.':'Pon tu obra frente a personas que están buscando arte en San Miguel.'}</h2></div><div><p>${en?'SMArt is built to bring artists, collectors, residents and hospitality projects together in one local platform.':'SMArt está pensado para conectar artistas, coleccionistas, residentes y proyectos de hospitalidad dentro de una plataforma local.'}</p><a class="market-button" href="${en?'/en/for-artists/':'/para-artistas/'}">${en?'Join SMArt':'Publicar mi obra'}</a></div></section></main><script>document.querySelectorAll('.market-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.market-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.market-card').forEach(c=>c.style.display=f==='*'||c.dataset.category===f?'block':'none')}));</script>`;return shell({en,head:commonHead({lang:en?'en':'es-MX',title,description,pathname,schema:{'@type':'CollectionPage',name:title,url:abs(pathname)}}),body})}
function artistsIndex(en=false){const pathname=en?'/en/artists/':'/artistas/';const title=en?'Artists in San Miguel de Allende | SMArt':'Artistas en San Miguel de Allende | SMArt';const description=en?'Discover artists presented by SMArt in San Miguel de Allende, their artwork, mural practice and commission possibilities.':'Descubre artistas presentados por SMArt en San Miguel de Allende, su obra, muralismo y posibilidades de proyectos por encargo.';const cards=publishedArtists.map(a=>`<a class="market-artist-card" href="${en?'/en/artists/':'/artistas/'}${esc(a.slug)}/"><figure><img src="${esc(a.image)}" alt="${en?'Artist working on an art project':'Artista trabajando en un proyecto artístico'}" loading="lazy"></figure><h2>${esc(a.name)}</h2><p>${esc((a.disciplines||[]).join(' · '))}</p></a>`).join('');const body=`<main class="market-page"><section class="market-page-hero"><div><div class="market-kicker">${en?'ARTISTS · SAN MIGUEL DE ALLENDE':'ARTISTAS · SAN MIGUEL DE ALLENDE'}</div><h1>${en?'Artists and practices worth discovering.':'Artistas y prácticas por descubrir.'}</h1></div><p>${en?'Meet the artists currently presented by SMArt and explore the work connected to each practice.':'Conoce a los artistas que actualmente presenta SMArt y explora las obras y proyectos vinculados con cada práctica.'}</p></section><section class="market-artist-grid">${cards}</section><section class="market-artist-cta"><div><div class="market-kicker">${en?'OPEN CALL':'CONVOCATORIA ABIERTA'}</div><h2>${en?'Are you an artist working in San Miguel?':'¿Eres artista y trabajas en San Miguel?'}</h2></div><div><p>${en?'SMArt is growing its local catalog. Tell us about your work and how you would like to participate.':'SMArt está ampliando su catálogo local. Cuéntanos sobre tu trabajo y cómo te gustaría participar.'}</p><a class="market-button" href="${en?'/en/for-artists/':'/para-artistas/'}">${en?'For artists':'Para artistas'}</a></div></section></main>`;return shell({en,head:commonHead({lang:en?'en':'es-MX',title,description,pathname,schema:{'@type':'CollectionPage',name:title,url:abs(pathname)}}),body})}
function artistPage(a,en=false){const pathname=`${en?'/en/artists/':'/artistas/'}${a.slug}/`;const works=publishedWorks.filter(w=>w.artistId===a.id);const title=`${a.name} | ${en?'Artist in San Miguel de Allende':'Artista en San Miguel de Allende'} | SMArt`;const description=en?a.bioEn:a.bioEs;const body=`<main class="market-page"><section class="market-artist-profile"><figure><img src="${esc(a.image)}" alt="${en?'Artist working on a painting project':'Artista trabajando en un proyecto de pintura'}"></figure><div class="market-artist-profile-copy"><div class="market-kicker">${esc(a.city)}</div><h1>${esc(a.name)}</h1><p>${esc(description)}</p><div class="market-chips">${(a.disciplines||[]).map(x=>`<span class="market-chip">${esc(x)}</span>`).join('')}</div><div class="market-inline-actions"><a class="market-button solid" href="${whatsapp(en?`Hello, I would like information about ${a.name}'s work.`:`Hola, quiero información sobre la obra de ${a.name}.`)}" target="_blank" rel="noopener">${en?'Inquire':'Consultar'}</a><a class="market-button" href="${en?'/en/artworks/':'/obras/'}">${en?'All artworks':'Todas las obras'}</a></div></div></section><section class="market-section"><div class="market-section-head"><div><div class="market-kicker">${en?'SELECTED WORK':'OBRA SELECCIONADA'}</div><h2>${en?'Artwork and projects':'Obra y proyectos'}</h2></div></div><div class="market-work-grid">${works.map(w=>workCard(w,en)).join('')}</div></section></main>`;return shell({en,head:commonHead({lang:en?'en':'es-MX',title,description,pathname,schema:{'@type':'ProfilePage',name:title,url:abs(pathname),mainEntity:{'@type':'Person',name:a.name,url:abs(pathname)}}}),body})}
function workPage(w,en=false){const a=artistById(w.artistId);const pathname=`${en?'/en/artworks/':'/obras/'}${w.slug}/`;const title=`${en?w.titleEn:w.titleEs} | ${a.name} | SMArt`;const description=en?w.descriptionEn:w.descriptionEs;const price=w.price!=null?`${w.currency||'MXN'} ${w.price}`:'';const details=[[en?'Artist':'Artista',a.name],[en?'Category':'Categoría',en?w.categoryEn:w.categoryEs],[en?'Medium':'Técnica',w.medium],[en?'Dimensions':'Medidas',w.dimensions],[en?'Availability':'Disponibilidad',en?w.statusEn:w.statusEs],[en?'Price':'Precio',price]].filter(x=>x[1]);const body=`<main class="market-page"><section class="market-work-page"><div class="market-work-image"><img src="${esc(w.image)}" alt="${esc(en?w.altEn:w.altEs)}"></div><div class="market-work-copy"><div class="market-kicker">${esc(en?w.categoryEn:w.categoryEs)}</div><h1>${esc(en?w.titleEn:w.titleEs)}</h1><a class="artist-link" href="${en?'/en/artists/':'/artistas/'}${esc(a.slug)}/">${esc(a.name)} →</a><p class="description">${esc(description)}</p><div class="market-details">${details.map(([k,v])=>`<div class="market-detail"><strong>${esc(k)}</strong><span>${esc(v)}</span></div>`).join('')}</div><div class="market-inline-actions"><a class="market-button solid" href="${whatsapp(en?`Hello, I would like information about “${w.titleEn}” by ${a.name}.`:`Hola, quiero información sobre “${w.titleEs}” de ${a.name}.`)}" target="_blank" rel="noopener">${en?'Inquire about this artwork':'Consultar esta obra'}</a><a class="market-button" href="${en?'/en/artworks/':'/obras/'}">${en?'Back to artworks':'Volver a obras'}</a></div></div></section></main>`;const schema={'@type':'VisualArtwork',name:en?w.titleEn:w.titleEs,image:abs(w.image),url:abs(pathname),description,creator:{'@type':'Person',name:a.name,url:abs(`${en?'/en/artists/':'/artistas/'}${a.slug}/`)}};return shell({en,head:commonHead({lang:en?'en':'es-MX',title,description,pathname,type:'article',schema}),body})}
function artistJoin(en=false){const pathname=en?'/en/for-artists/':'/para-artistas/';const title=en?'For Artists | Publish Your Artwork in San Miguel de Allende | SMArt':'Para Artistas | Publica tu Obra en San Miguel de Allende | SMArt';const description=en?'Join the growing SMArt catalog and present artwork, commissions and projects to people looking for art in San Miguel de Allende.':'Forma parte del catálogo de SMArt y presenta obra, encargos y proyectos a personas que buscan arte en San Miguel de Allende.';const body=`<main class="market-page"><section class="market-page-hero"><div><div class="market-kicker">${en?'SMArt FOR ARTISTS':'SMArt PARA ARTISTAS'}</div><h1>${en?'Your work belongs in the conversation.':'Tu obra también puede estar aquí.'}</h1></div><p>${en?'SMArt is building a local marketplace where artists can present work and connect with collectors, residents, hotels, restaurants and commissioned projects.':'SMArt está construyendo un marketplace local donde artistas pueden presentar obra y conectar con coleccionistas, residentes, hoteles, restaurantes y proyectos por encargo.'}</p></section><section class="market-paths"><div class="market-path"><div class="market-kicker">${en?'PUBLISH ARTWORK':'PUBLICAR OBRA'}</div><h2>${en?'Build your artist profile and catalog.':'Crea tu perfil y catálogo de artista.'}</h2><p>${en?'Each artist can have a profile, artwork listings, availability and direct inquiry. New profiles are reviewed before publication.':'Cada artista puede tener perfil, fichas de obra, disponibilidad y consulta directa. Los nuevos perfiles se revisan antes de publicarse.'}</p><div class="market-inline-actions"><a class="market-button solid" href="${whatsapp(en?'Hello, I am an artist and I would like to publish my work on SMArt.':'Hola, soy artista y quiero publicar mi obra en SMArt.')}" target="_blank" rel="noopener">${en?'Apply as artist':'Quiero publicar mi obra'}</a></div></div><div class="market-path"><div class="market-kicker">${en?'PROJECTS & COMMISSIONS':'PROYECTOS Y ENCARGOS'}</div><h2>${en?'Get considered for commissions and spaces.':'Participa en encargos y proyectos para espacios.'}</h2><p>${en?'SMArt also connects artistic practices with murals, signage, hospitality and custom commissions.':'SMArt también conecta prácticas artísticas con murales, rótulos, hospitalidad y comisiones personalizadas.'}</p></div></section></main>`;return shell({en,head:commonHead({lang:en?'en':'es-MX',title,description,pathname,schema:{'@type':'WebPage',name:title,url:abs(pathname)}}),body})}
function injectAfterHero(html,markup){const s=html.indexOf('<section class="ref-hero">');if(s<0)return html;const e=html.indexOf('</section>',s);if(e<0)return html;return html.slice(0,e+10)+markup+html.slice(e+10)}
function marketHomeBlock(en=false){const featured=publishedWorks.filter(x=>x.featured!==false).slice(0,4);const a=publishedArtists.find(x=>x.featured)||publishedArtists[0];return `<section class="market-home-intro"><div><div class="market-kicker">${en?'ART · ARTISTS · SAN MIGUEL DE ALLENDE':'ARTE · ARTISTAS · SAN MIGUEL DE ALLENDE'}</div><h2>${en?'Artwork to collect. Art to transform spaces.':'Obras para coleccionar. Arte para transformar espacios.'}</h2></div><p>${en?'SMArt brings together artwork, local artists and custom artistic services in one San Miguel de Allende platform.':'SMArt reúne obra, artistas locales y servicios artísticos por encargo dentro de una sola plataforma de San Miguel de Allende.'}</p></section><section class="market-section"><div class="market-section-head"><div><div class="market-kicker">${en?'MARKETPLACE':'MARKETPLACE'}</div><h2>${en?'Featured artworks':'Obras destacadas'}</h2></div><a href="${en?'/en/artworks/':'/obras/'}">${en?'Explore all artworks →':'Explorar todas las obras →'}</a></div><div class="market-work-grid">${featured.map(w=>workCard(w,en)).join('')}</div></section>${a?`<section class="market-artist-feature"><div class="market-artist-image"><img src="${esc(a.image)}" alt="${en?'Artist working on an art project':'Artista trabajando en un proyecto artístico'}" loading="lazy"></div><div class="market-artist-copy"><div class="market-kicker">${en?'FEATURED ARTIST':'ARTISTA DESTACADO'}</div><h2>${esc(a.name)}</h2><p>${esc(en?a.bioEn:a.bioEs)}</p><div class="market-inline-actions"><a class="market-button solid" href="${en?'/en/artists/':'/artistas/'}${esc(a.slug)}/">${en?'View artist':'Ver artista'}</a><a class="market-button" href="${en?'/en/artists/':'/artistas/'}">${en?'All artists':'Todos los artistas'}</a></div></div></section>`:''}<section class="market-paths"><div class="market-path"><div class="market-kicker">${en?'DISCOVER ART':'DESCUBRE ARTE'}</div><h2>${en?'Find work made in and connected to San Miguel.':'Encuentra obra hecha en y conectada con San Miguel.'}</h2><p>${en?'Browse artists and artwork, then inquire directly about availability and details.':'Explora artistas y obra, y consulta directamente disponibilidad y detalles.'}</p><a class="market-button" href="${en?'/en/artworks/':'/obras/'}">${en?'Explore artworks':'Explorar obras'}</a></div><div class="market-path"><div class="market-kicker">${en?'COMMISSION ART':'CONTRATA ARTE'}</div><h2>${en?'Murals, signs and custom commissions.':'Murales, rótulos y obra por encargo.'}</h2><p>${en?'For homes, businesses, hotels, restaurants and spaces that need something unique.':'Para residencias, negocios, hoteles, restaurantes y espacios que necesitan algo único.'}</p><a class="market-button dark" href="${en?'/en/murals-san-miguel-de-allende/':'/murales-san-miguel-de-allende/'}">${en?'See art services':'Ver servicios artísticos'}</a></div></section>`}
function patchHome(html,en=false){if(!html.includes('/assets/css/marketplace.css'))html=html.replace('</head>','<link rel="stylesheet" href="/assets/css/marketplace.css"></head>');html=html.replace(/<title>[\s\S]*?<\/title>/,`<title>${en?'Art in San Miguel de Allende | Artists, Artworks, Murals & Signs | SMArt':'Arte en San Miguel de Allende | Obras, Artistas, Murales y Rótulos | SMArt'}</title>`);html=html.replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${en?'Discover artists and artwork in San Miguel de Allende, plus murals, hand-painted signs and custom commissions through SMArt.':'Descubre artistas y obra en San Miguel de Allende, además de murales, rótulos pintados a mano y proyectos por encargo con SMArt.'}">`);html=html.replace(/(<div class="ref-hero-copy">[\s\S]*?<h1>)[\s\S]*?(<\/h1>)/,`$1${en?'Art made in San Miguel de Allende.':'Arte hecho en San Miguel de Allende.'}$2`);html=html.replace(/(<div class="ref-hero-copy">[\s\S]*?<p>)[\s\S]*?(<\/p>)/,`$1${en?'Artwork to discover and collect. Art to transform spaces.':'Obras para descubrir y coleccionar. Arte para transformar espacios.'}$2`);html=html.replace(/<div class="hero-actions">[\s\S]*?<\/div>/,`<div class="hero-actions"><a class="button solid" href="${en?'/en/artworks/':'/obras/'}">${en?'EXPLORE ARTWORKS':'EXPLORAR OBRAS'}</a><button class="button" data-interest="${en?'Art project':'Proyecto artístico'}">${en?'REQUEST A QUOTE':'COTIZAR PROYECTO'}</button></div>`);if(!html.includes('market-home-intro'))html=injectAfterHero(html,marketHomeBlock(en));return html}
function enhanceExisting(html,en=false){if(!html.includes('/assets/css/marketplace.css'))html=html.replace('</head>','<link rel="stylesheet" href="/assets/css/marketplace.css"></head>');if(!html.includes(en?'/en/artworks/':'/obras/')){html=html.replace('<nav class="nav">',`<nav class="nav"><a href="${en?'/en/artworks/':'/obras/'}">${en?'Artworks':'Obras'}</a><a href="${en?'/en/artists/':'/artistas/'}">${en?'Artists':'Artistas'}</a>`);html=html.replace('<nav class="mobile-nav">',`<nav class="mobile-nav"><a href="${en?'/en/artworks/':'/obras/'}">${en?'Artworks':'Obras'}</a><a href="${en?'/en/artists/':'/artistas/'}">${en?'Artists':'Artistas'}</a>`)}return html}
async function patchExistingPages(){for(const p of Object.values(site.pages||{})){const rel=p.path==='/'?'index.html':path.join(p.path.replace(/^\//,'').replace(/\/$/,''),'index.html');const file=path.join(OUT,rel);try{let html=await readFile(file,'utf8');const en=String(p.lang).startsWith('en');html=enhanceExisting(html,en);if(p.path==='/'||p.path==='/en/')html=patchHome(html,en);await writeFile(file,html,'utf8')}catch{}}}
async function updateSitemap(){const file=path.join(OUT,'sitemap.xml');let xml='';try{xml=await readFile(file,'utf8')}catch{return}const urls=['/obras/','/artistas/','/para-artistas/','/en/artworks/','/en/artists/','/en/for-artists/',...publishedWorks.flatMap(w=>[`/obras/${w.slug}/`,`/en/artworks/${w.slug}/`]),...publishedArtists.flatMap(a=>[`/artistas/${a.slug}/`,`/en/artists/${a.slug}/`])];const add=urls.filter(u=>!xml.includes(`<loc>${abs(u)}</loc>`)).map(u=>`<url><loc>${abs(u)}</loc></url>`).join('');xml=xml.replace('</urlset>',add+'</urlset>');await writeFile(file,xml,'utf8')}

await patchExistingPages();
await writeRoute('/obras/',worksIndex(false));
await writeRoute('/en/artworks/',worksIndex(true));
await writeRoute('/artistas/',artistsIndex(false));
await writeRoute('/en/artists/',artistsIndex(true));
await writeRoute('/para-artistas/',artistJoin(false));
await writeRoute('/en/for-artists/',artistJoin(true));
for(const a of publishedArtists){await writeRoute(`/artistas/${a.slug}/`,artistPage(a,false));await writeRoute(`/en/artists/${a.slug}/`,artistPage(a,true))}
for(const w of publishedWorks){await writeRoute(`/obras/${w.slug}/`,workPage(w,false));await writeRoute(`/en/artworks/${w.slug}/`,workPage(w,true))}
await updateSitemap();
console.log(`SMArt marketplace built: ${publishedArtists.length} artists, ${publishedWorks.length} artworks/projects.`);
